### ISSUE TITLE
nw.exe has stopped working

### ISSUE THREAD

**Issue by jloa** [node-ffi/node-ffi#143]
On windows 7 mw.exe crashes all the time.
I'm trying to use this module >> https://npmjs.org/package/ffi
I've installed the module in my app's dir and wrote a simple app, here's the index.html:

```
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Test</title>
    </head>
    <body>
        <script>
        var FFI = require('ffi');
        </script>
    </body>
</html>
```

When i launch the app nw.exe dies. Any ideas?

**Comment by riadd** [comment]
So what was the fix for this issue?
