### ISSUE TITLE
How to deal with a char* return type

### ISSUE THREAD

**Issue by giuliomoro** [node-ffi/node-ffi#152]
So I have a c function with this prototype

```
char *GetResult(int resultHandle);
```

which I want to call from ffi.
Therefore I set 

```
var mylib = ffi.Library('libmylib', {
  'GetResult': [ 'char *', [ 'int'] ]
});
```

and I call

```
var results=ls.GetResult(5);
console.log(JSON.stringify(results));
```

The output to the console is : 

{"0":123,"length":1,"type":{"alignment":1,"name":"char","ffi_type":{"length":0,"name":"char"}}}

What am I doing wrong?
How can I retrieve the content of the char \* buffer returned by the function?
Thanks

**Comment by sarkiroka** [comment]
How can I pass a char array in return value? My c signature is int roka(char * val)
I use ffi in this way:
var lib = ffi.Library('mylib', {roka:['int', ['char*']]});
How can I access to modified val parameter? And how can I declare it a correct way?

**Comment by kelvinh** [comment]
@TooTallNate Thanks, finally I can get my `void callback(const char *data, size_t size)` work now... And I agree with @giuliomoro it would be nice if this info could be put into the wiki.

**Comment by GAURAV29** [comment]
@TooTallNate 
What is meant by  reinterpret(rawDataByteLength)??
I am facing the same issue. My return type is 'int16*' . How to read full returned data??

**Comment by 13456247300** [comment]
@GAURAV29 
I am facing the same issue. How do you solve this problem
