### ISSUE TITLE
Fails to build with node 0.11

### ISSUE THREAD

**Issue by parasyte** [node-ffi/node-ffi#159]
I know 0.11 is currently unstable, but it would be good to prepare for the coming stable 0.12 release, right? :wink:

`ref` was recently updated for 0.11 support: https://github.com/TooTallNate/ref/issues/10

**Comment by andymorris** [comment]
Any update on this? Any way I can help?

I'm trying to use node-ffi in an atom-shell app. I was getting by with the fork @avatar5d posted and atom-shell 0.15.9, but `apm install` just stopped working. My guess is that my install of Atom auto-updated, which updated apm, but I'm not sure.

**Comment by kjunichi** [comment]
Hi, @andymorris.
It's been long time.
I posted some message about this.  Issuse #187

**Comment by lygstate** [comment]
This can be mark as fixed.
