### ISSUE TITLE
Any hopes for https://github.com/npm/npm/issues/1891?

### ISSUE THREAD

**Issue by GulinSS** [node-ffi/node-ffi#166]
Do you plan to move current build process to similar https://github.com/sass/node-sass/commit/d4ffe84a77a7ae6820112b9cae5030abc48e759e or https://github.com/mapbox/node-pre-gyp?

**Comment by unbornchikken** [comment]
No. Considering the change frequency of the io.js project and v8 internals, this is gonna take way too mutch effort for a little or no gain. On little or no gain I mean if some modules provide binaries and others are not, and aplications have been using a mix of those, then you gotta have a proper compiler toolchain anyway, right?
