### ISSUE TITLE
How to read char* value?

### ISSUE THREAD

**Issue by Akudrevatykh** [node-ffi/node-ffi#169]
I have a sample C code:

    #include <string.h>
    #include <stdio.h>
    int test(char* str, int len)
    {
	 char str1[]="sample str\0";
	 strcpy(str, str1);
	 return sizeof(str1);
    }

I am trying to read the value written to char* str:

```javascript
exports.test = new FFI.Library('./test', {
     test: [ref.types.int32, [
  ref.types.CString,
   ref.types.int32,
   ]],
 });

var buf = new Buffer(100);
buf.type = ref.types.CString;

var ret_len = exports.test.test(buf.deref(), buf.length);

console.log(buf);
console.log(buf.deref());
console.log(buf.toString());
console.log(buf.deref().toString());
console.log(ref.readCString(buf,0));
```

But that returns garbage characters :\

**Comment by TooTallNate** [comment]
Sorry for taking so long here. This should be fixed as of `ref@1.1.2`. Let me know if you have any issues using the `"string"` type going forward!

**Comment by BONDbATIF** [comment]
var express=require('express')
;
var ffi=require('ffi')
;
var ref=require('ref')
;
var filePath="D:/node_web_Dev/gettingJson/dll/Win32Project1";
 testData=ffi.Library(filePath,{
    "test":["char *",[]]
});

var josnString=testData.test();
var saveData=josnString.readCString();

//call the function
//theStringBuffer=testData.test();
console.log('\n');
console.log(saveData);

getting junk value each time different different like  "��0"

**Comment by YOSSTM** [comment]
what if I have this in my c code 
struct {
char data[30];}

I tried 
data:ArrayType('char',33) but I got wrong results
