### ISSUE TITLE
can node-ffi support c++ library?

### ISSUE THREAD

**Issue by ericmayc** [node-ffi/node-ffi#170]
Hi guys,

I scan lots of issues, all use node-ffi with c library. Can node-ffi support c++ library?

How about performance of node-ffi? Are you satisfied with the performance of node-ffi? Do you have benchmark?

**Comment by TooTallNate** [comment]
Ya I mean not officially, but I believe that the C++ ABI is similar enough that it _usually just works_, but I believe you have to do the C++ symbol name mangling manually, which is outside the scope of this module. Could be a cool separate module though!
