### ISSUE TITLE
How to deal with optional parameters?

### ISSUE THREAD

**Issue by rodrigopandini** [node-ffi/node-ffi#175]
Hi, 
I have a function in a dll that has a optional parameter.
like this:
```js
var lib = ffi.Library(myLib, {
  "myFunc": ["int", ["string"]]
});
lib.myFunc();
```
Since the "string" argument is optional, should I declare it in the declarations section?
There is other way to say that it is optional?
Will the call of `lib.myFunc()` causes `ffi` throw a error, since there is not enough parameters? 
How to deal with this?

Great project, by the way!

**Comment by TooTallNate** [comment]
Optional function parameters do not exist in C... what library are you trying to interact with?

**Comment by unbornchikken** [comment]
Too old, no feedback, closed. @rodrigopandini if you could put there your C side of code, then please open up this issue again.
