### ISSUE TITLE
Pass enum as argument in foreign function

### ISSUE THREAD

**Issue by binoddokania** [node-ffi/node-ffi#176]
I am looking for a way to pass the enum as  argument in foreign function through node-ffi.
I have already installed enum module using npm install enum

``` js
var myEnum = require('enum');
var myTestenum = new myEnum({'key1':1,'key2':2});

var myFF= ffi.Library('someLib', {
     'someFn': [ 'int', ['myTestenum '] ]
   });

myFF.someFn(myTestenum .key1);
```

but it does not work. I think I am not passing correct argument data type during declaration.

**Comment by TooTallNate** [comment]
That `enum` module doesn't work with ref/node-ffi. I wonder if they'd be willing to accept a PR making it a proper "type"...

As a workaround, just use `"int"` as the type.

**Comment by goel-sunny** [comment]
@TooTallNate  have you create any enum prototype in ffi module .
