### ISSUE TITLE
how to use get return value that the type is 'enum'?

### ISSUE THREAD

**Issue by lineargb35** [node-ffi/node-ffi#179]
Here is the code in C ...

typedef enum MyEnum {
    AAA,
    BBB,
    CCC
} MyEnumdef ;

MyEnumdef myFunction(int x, int y);

I want to call this function using ffi, but I don't know how to do it.
I don't know what the correct data type is. 
Is there any solution for me? Thanks!

**Comment by TooTallNate** [comment]
You can use `"int"` as the type for enums. Ideally we'd write a `ref-enum` module some day!

**Comment by cocobiz** [comment]
hi @TooTallNate 
Is this scheme suitable for enumeration in parameters?
