### ISSUE TITLE
Dynamic Linking Error,  unsupported file type error 

### ISSUE THREAD

**Issue by Secure-Labs** [node-ffi/node-ffi#185]
I saw similar errors here in this issue tracker and on stackoverflow, but I didn't see any that had the same error code "unsupported file type error" or that solved the linking error. Here is the error code...

```
/usr/local/www/nginx-dist/node_modules/ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
          ^
Error: Dynamic Linking Error: /usr/lib/libHelloWorld.so: unsupported file type
    at new DynamicLibrary (/usr/local/www/nginx-dist/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.Library (/usr/local/www/nginx-dist/node_modules/ffi/lib/library.js:45:12)
    at Server.<anonymous> (/usr/local/www/nginx-dist/server.js:8:25)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2113:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socket.ondata (http.js:1971:22)
    at TCP.onread (net.js:528:27)
```

and the library...

``` c
#include "helloWorld.h"
#include <stdlib.h>
#include <string.h>

int helloWorld(char **response)
{
    int rtrn;

    rtrn = asprintf(response, "hello world!");
    if(rtrn < 0)
    {
        return -1;
    }

    return 0;
}
```

header..

``` c
#ifndef HELLO_WORLD_H
#define HELLO_WORLD_H

#include <stdio.h>

/* Test function. */
extern int helloWorld(char **response);

#endif
```

and here is the flags I used to compile it...

```
-c -fpic -Wall -Werror -Weverything -Wno-deprecated-declarations -g -fstack-protector-all -O3 -Wno-newline-eof -Wno-padded
```

this is the node app, it crash when you use a browser to go to http:putInYourIpAddr:8888.

``` js
var http = require("http");
var ffi = require("ffi");
var ref = require('ref');

http.createServer(function(request, response) {
  var callLibrary = ffi.Library('libCallApi', {
    "helloWorld": [ 'void',  [ 'charPtrPtr' ] ]
   });

  var string = ref.alloc('int');
  callLibrary.helloWorld(string);
  var actualString = string.deref();
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.write(string);
  response.end();
}).listen(8888);
```

This was compiled and ran on freebsd 10.1 x64 and my node is x64 according to node -pe "process.arch", I saw that was causing other people problems, but the architectures for the binary, the node app and the library match up.  I am unsure of whats wrong and any help would be appreciated.

**Comment by unbornchikken** [comment]
This issue is not realted to ffi library, because its use dlopen system call to load libraries. If it fails with the error of the above, that means something wrong with the library, maybe it compiled with inapropriate flags. See: http://marc.info/?l=freebsd-hackers&m=94347318602761

I suggest that create a C project and reference your library with dlopen, and see if the error result gives something more accurate.
