### ISSUE TITLE
little problem in the first page https://github.com/node-ffi/node-ffi

### ISSUE THREAD

**Issue by SabHattay** [node-ffi/node-ffi#188]
In the first page : https://github.com/node-ffi/node-ffi

we see : git clone git://github.com/node-ffi/node-ffi.git

And I think it's 
git clone https://github.com/node-ffi/node-ffi.git

**Comment by TooTallNate** [comment]
Both of those syntaxes will work. The first one goes over ssh+git protocol, the later with https protocol.
