### ISSUE TITLE
unable to read content of out parameter

### ISSUE THREAD

**Issue by mikeliucc** [node-ffi/node-ffi#190]
I'd apologize on the outset if this is a silly question.  After trying to resolving this issue on my own attempt for almost an entire day, this is my last resort.  Please help...

Here's what I have:
A DLL with the following methods:

...
    #region DLL Import Declarations
    [DllImport(@"test.DLL", EntryPoint="functionA", CharSet=CharSet.Ansi)]
    private static extern int functionA(int num);

    [DllImport("test.DLL", EntryPoint="functionB", CharSet=CharSet.Ansi)]
    private static extern int functionB(StringBuilder aData, ref int aMaxSize, int fmt);
...

in my nodejs project, I have:

var intPtr = ref.refType('int');
var stringBuilder = ref.types.void;
var stringBuilderPtr = ref.refType(stringBuilder);

var myDLL = new ffi.Library('test.dll', {
    'functionA'    : ['int32', ['int32']],
    'functionB': ['int32', ['pointer', intPtr, 'int32']]
});

console.log(myDLL.functionA(14));  // works fine!

var outString = ref.alloc('string');
var outNumber = ref.alloc('int');
outNumber.writeInt32LE(0, 0);

console.log(myDLL.functionB(outString, outNumber, 1));

console.log('outString.length = ' + outString.length);   // always output 4

var out = outString.deref();
console.log(out);  // gibberish. e.g.  p�$�.`M9`M9`M9`M9`M90�$0�5p�$�.M9`M9`M9`M9`M9M9�N#p�$

---------------------

The question is how do I read the content of the 'out' buffer.  It seems to be pointing to some gibberish, mostly 76 bytes but sometimes 3 bytes.  Based on what I know functionB should return XML string.

Thanks in advance!

**Comment by TooTallNate** [comment]
So is `StringBuilder` a `char **` type then basically?

**Comment by mikeliucc** [comment]
StringBuilder is a C# type, which, accordingly to MSDN, works like String with better performance.

Suppose we should use char **, would you suggest that I create "pointer-to-pointer" to ref.types.void?

Thanks

**Comment by mikeliucc** [comment]
Based on what I can find, I think we can assume the native call to be something like this:
   int functionB(char *aData, int *aMaxSize);

Assuming the above is right, how do I pass-by-reference a JS variable as the first parameter, and read its content after the native call is made?

Thanks!

**Comment by mikeliucc** [comment]
finally figured out my problem -- a word of advise for those that might run into the same issue: READ THE DOCUMENTATION!

It turns out that the DLL is requiring a double call - once to get the buffer size, and second time to assign data to the buffer parameter (out param) with the right size set.  Once I set up my code as such, things start to work.  Dang...
