### ISSUE TITLE
The dll has bug to popup window of error and result I/O for V8 JavaScript can't response.

### ISSUE THREAD

**Issue by windwaterbo** [node-ffi/node-ffi#192]
Hi,

I have a problem recently. I coded a dll that has some bug. When the wrong was happened, it could popup a window of error as follow.

![Microsoft Visual C++ Runtime Library (can't response)](https://copy.com/kOxfHH0hjMXTAe69)

If I ignore the window of error, the I/O for V8 will be blocked.

![Evented I/O for V8 JavaScript can not response](https://copy.com/MFHETRDqUj8OezYP)

How can I stop the Evented I/O for V8 from being blocked? Can I do anything with nodejs except fixing the dll to overcome this problem?

**Comment by TooTallNate** [comment]
You could possibly try calling the function that is causing the window to popup on the thread pool. So call the function with `.async()`.

**Comment by windwaterbo** [comment]
The dll has error that causeing the window to popup,"Debug Assertion Failed". Howerver, this result to I/O V8 hang out there and it can't release memory. For these reasons lead to I/O V8 dead.

How can I do to release the dead of events for I / O, so that it can continue to handle other event

**Comment by TooTallNate** [comment]
Did you try calling the FFI function with `.async()` like I suggested before?

**Comment by windwaterbo** [comment]
Yes , I has used it always.

**Comment by TooTallNate** [comment]
Can you show me your code?

**Comment by windwaterbo** [comment]
```javascript
module.exports.interface = function (restfulRoute, queryString,res,callback) {
...
...
user32.parseQIDOForSeries.async(httpRequest, len, dbPtrPtr, outNumber, LOGdbPtrPtr, LOGoutNumber, LOGIDNumber, 0, serverSite, function (err, x, data) {
                if (err) throw err;
                Response = dbPtrPtr.deref();
                LOGResponse = LOGdbPtrPtr.deref();
                LOGIDResponse = LOGIDNumber.deref();
                callback(err, Response, LOGResponse, LOGIDResponse);
});
}
```

**Comment by TooTallNate** [comment]
Hmmm... Well the window must be running on the same thread as Node.js then. I'm not sure if there's going to be anything we can do about that unfortunately.

**Comment by windwaterbo** [comment]
Is there any other way to do it?  How do I  allocated to  other thread, not on the same .

**Comment by vitaly-t** [comment]
The thread could be windowless, i.e. worker thread that doesn't have the window events pumped through it, hence the error. Another reason, since it is VC++, it could require additional initialization before UI can be accessed.

**Comment by windwaterbo** [comment]
@vitaly-t  My dll don't use built-in function on VC .
@vitaly-t thnks @TooTallNate thanks for your reply . I fix my dll bug at the last  , however , I want to enhance server stablity with nodejs .

**Comment by windwaterbo** [comment]
I fix bug from my dll . not nodejs . But.. thanks a lot .
