### ISSUE TITLE
Callback gets crashed on Windows

### ISSUE THREAD

**Issue by unbornchikken** [node-ffi/node-ffi#199]
Under some unobvious circumstances, libuv's `uv_thread_self()` gives NULL on Windows. And because of this `CallbackInfo::Invoke()` thinks that it is running on main node thread:

```C++
uv_thread_t self_thread = (uv_thread_t) uv_thread_self();
if (uv_thread_equal(&self_thread, &g_mainthread)) { ...
```

If `uv_thread_self()` gives NULL then the above will always true and DispatchToV8 called on the thread that the foreign function uses to call back our callback. :) I'm getting it with my [NOOOCL module](https://github.com/unbornchikken/NOOOCL), where OpenCL event callbacks are invoked on different threads. And of course on an OpenCL thread there isn't a V8 Isolate instance, so `WrapPointer` method's first line (`NanEscapableScope()`) crases with an access violation.

In "unobvious circumstances" I mean I am not geting this libuv issue on my work machine (Windows 8.1 x64). On my home machine I am (Windows 7 x64). Reporter of this issue is getting it: https://github.com/unbornchikken/NOOOCL/issues/2 (Windows 8.1). So I made a PR, where there is a workaround, on Windows `GetCurrentThreadId()` will determine if we're on node thread or not when called back.

**Comment by unbornchikken** [comment]
If anyone's suffering from this, I've applied the patch to my [ffi-io](https://github.com/unbornchikken/node-ffi) fork, you can use it instead of ffi till the above PR gets merged.

**Comment by toxickg** [comment]
Looks like I have the same issue. I'm making a call to a function of my custom DLL passing a callback in parameters. This callback is fired on a different thread inside the library and the application just hangs in this case.

I use `ffi` module from an Atom Shell (which is based on io.js) application on Windows 8.1 x64.

The fork you suggested gets the job done. Gábor, thank you very much for the fix!
