### ISSUE TITLE
Pointer to pointer of struct?

### ISSUE THREAD

**Issue by dubcanada** [node-ffi/node-ffi#203]
Hello,

I am trying to get libgphoto2 working which requires a `gp_camera_new` with a passed in pointer to a pointer

C

    Camera  *canon;
    GPContext *canoncontext;

    canoncontext= sample_create_context();
    gp_camera_new(&canon);

or http://www.gphoto.org/doc/api/gphoto2-camera_8c.html#ad89d6ee1c35f5ee399e89ecaeac6bd61

And I have the following code in node

    var ffi = require('ffi')
    var ref = require('ref');

    var retval;

    var GPCameraFile = ref.types.void; // CameraFile is LibGphoto struct
    var CameraFilePtr = ref.refType(GPCameraFile);

    var GPContext = ref.types.void; // GPContext is LibGphoto struct
    var GPContextPtr = ref.refType(GPContext);
    var Context = ref.alloc(GPContextPtr);

    var GPCamera = ref.types.void; // GPCamera is LibGphoot struct I would need pointer to pass to lib APIs
    var GPCameraPtr = ref.refType(GPCamera);
    var Camera = ref.alloc(GPCameraPtr)

    var libgphoto = ffi.Library('libgphoto2.dylib', {
      'gp_camera_new': [ 'void', [ 'pointer' ] ],
      'gp_context_new': [ 'pointer', [  ] ],
      'gp_camera_capture_preview': [ 'int', [ 'pointer','pointer' ,'pointer' ] ],
      'gp_camera_init': [ 'int', [ 'pointer','pointer' ] ]
    })

    Context = libgphoto.gp_context_new.async(function(err, res) {
        Camera = libgphoto.gp_camera_new.async(Context, function(err, res) {
            console.log(res, err);
        })
    });

And I keep getting an error

    [TypeError: error setting argument 0 - writePointer: Buffer instance expected as third argument]

Which is being triggered by `libgphoto.gp_camera_new`, I've tried with async, without async, etc etc.

Do pointers to pointers not work properly? Or anyone have any idea as to what is up?

**Comment by unbornchikken** [comment]
Would you create a gist from the console output by running it with DEBUG=ffi:*?

**Comment by unbornchikken** [comment]
But:

```js
'gp_camera_new': [ 'void', [ 'pointer' ] ],
```

should be: 

```js
'gp_camera_new': [ 'void', [ ref.refType(ref.refType("void")) ] ],
```

And should be called like this:

```js
var GPCamera = ref.refType("void"); 
var GPCameraRef = ref.refType(GPCamera);

var gpCameraResult = ref.alloc(GPCameraRef);
libgphoto.gp_camera_new(gpCameraResult);
var gpCamera = gpCameraResult.deref();
```
