### ISSUE TITLE
cannot install ffi with win8.1x64/vs2013update4/python2.7.3/node 0.12.3

### ISSUE THREAD

**Issue by ashareye** [node-ffi/node-ffi#205]
fail to npm install ffi, and npm-debug.log is:

1164 info install ref@1.0.2
1165 verbose unsafe-perm in lifecycle true
1166 info ref@1.0.2 Failed to exec install script
1167 verbose unlock done using C:\Users\ashare\AppData\Roaming\npm-cache\_locks\ref-26473bd1340fbb09.lock for Y:\working\code\test\nodejs\test.dll\node_modules\ffi\node_modules\ref
1168 verbose about to build Y:\working\code\test\nodejs\test.dll\node_modules\ffi
1169 verbose unlock done using C:\Users\ashare\AppData\Roaming\npm-cache\_locks\ffi-c59778bcfbfe0925.lock for Y:\working\code\test\nodejs\test.dll\node_modules\ffi
1170 verbose stack Error: ref@1.0.2 install: `node-gyp rebuild`
1170 verbose stack Exit status 1
1170 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
1170 verbose stack     at EventEmitter.emit (events.js:110:17)
1170 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
1170 verbose stack     at ChildProcess.emit (events.js:110:17)
1170 verbose stack     at maybeClose (child_process.js:1015:16)
1170 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
1171 verbose pkgid ref@1.0.2
1172 verbose cwd Y:\working\code\test\nodejs\test.dll
1173 error Windows_NT 6.3.9600
1174 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ffi" "--save"
1175 error node v0.12.3
1176 error npm  v2.9.1
1177 error code ELIFECYCLE
1178 error ref@1.0.2 install: `node-gyp rebuild`
1178 error Exit status 1
1179 error Failed at the ref@1.0.2 install script 'node-gyp rebuild'.
1179 error This is most likely a problem with the ref package,
1179 error not with npm itself.
1179 error Tell the author that this fails on your system:

how can i solve it?

**Comment by unbornchikken** [comment]
it seems youre having problem with the ref module that ffi depend on. please report this bug there too till i get some time to investigate. thanks.

**Comment by unbornchikken** [comment]
I cannot reproduce this. It builds and runs tests fine at my side on Win8.1 x64 / node 0.12.4. If you've installed new version of node before you installed ffi, then please delete node_modules folder in your project's root then do an `npm install`. That will refresh NAN in all of modules and their dependencies.

**Comment by unbornchikken** [comment]
Not reproducible.
