### ISSUE TITLE
How to get a return value 'char*'?

### ISSUE THREAD

**Issue by lizterminator** [node-ffi/node-ffi#206]
my c++ code：

EXPORT char* getBuf(int x, int y, int l,int* len)
{
	FILE *fin = fopen("a.jpg", "rb");
	char* buf = (char*)malloc(sizeof(char) * 1024 * 1024);
	*len = fread(buf, 1, 1024 * 1024, fin);
	return buf;
}

EXPORT void releaseBuf(char* buf)
{
	free(buf);
}

then in my node code:

var libm = ffi.Library(__dirname+'\\readfile.dll', {
  'getBuf':['char *',['int','int','int',intPtr]
});

and i use:
var l = ref.alloc(ref.types.int);
var bits = ref.alloc('char *');
bits = libm.getBuf(1,2,3,l);

I can get the 'l' successfully, but  the bits.length===1?

what should i do to get the file(a.jpg)?

**Comment by TooTallNate** [comment]
Use "string" as the type instead of "char *".

"string" is a special type that reads a null-terminated C-style string.

**Comment by lizterminator** [comment]
thank you. i use "string", and i use var bits = libm.getBuf(1,2,3,l). buti still can not get the buffer that i want.

I am trying to serve this image to front end.

var server = http.createServer(function(req,res){
	
	res.writeHead(200,{'Content-Type':'img/jpeg'});
	res.write(bits,'binary');
	res.end();
}).listen(4000);

**Comment by unbornchikken** [comment]
In case if it's a binary file, the result char * should be threatened as a pointer. And because it isn't zero terminated you should reinterpret it to make it have the result length.

```js
var libm = ffi.Library(__dirname+'\readfile.dll', {
'getBuf':['pointer',['int','int','int',intPtr]
});

var l = ref.alloc(ref.types.int);
var ptr = libm.getBuf(1,2,3,l);
var len = l.deref();
var bits = ref.reinterpret(ptr, len, 0);
```

**Comment by lizterminator** [comment]
thanks very much! It works! memeda..
