### ISSUE TITLE
Can't run node-ffi example on Windows 7 or XP

### ISSUE THREAD

**Issue by danielyaa5** [node-ffi/node-ffi#208]
So I was able to run the example from the wiki page no problem.... on Mac.

But for some reason whenever I try to do the installation on a PC I can't run the example. I double checked to make sure Im doing the installation right (installing node-gyp globally, installing python and visual studio 2013 express). But when I try to run the example I get the error message saying something like 

throw new Error('Dynamic Linking Error: ' + err)
Error: Dynamic Linking Error: "libm.dll": The specified module could not be found.

The full error message in the command prompt can be seen in the picture below.
![ffi-error](https://cloud.githubusercontent.com/assets/6629098/7964437/bb4086d4-09e5-11e5-897d-34e36f7bb3da.png)

I've tried this on a windows 7 and windows xp computer and get the same error when trying to run the example. My coworker said that I cant load dll's if using node-ffi on a Mac, only .os files, is this true?

Thanks in advance for any help.

**Comment by rodrigopandini** [comment]
Try check if the path for dll is correct.
I can run the example on win7 - 64bits.

You can use something like the code bellow to load in each platform without change your code:
```js
var os = require("os"),
  path = require("path"),
  ffi = require("ffi"),
  ref = require("ref");

var filePath = "";

if ((os.platform() === "win32") || (os.platform() === "win64")) {
  if (os.arch() === "ia32") {
    filePath = path.join(__dirname, "dll", "32", "myWinLib");
  } else if (os.arch() === "x64") {
    filePath = path.join(__dirname, "dll", "64", "myWinLib");
  }
} else if (os.platform() === "linux") {
  if (os.arch() === "ia32") {
    filePath = path.join(__dirname, "so", "32", "myLib");
  } else if (os.arch() === "x64") {
    filePath = path.join(__dirname, "so", "64", "myLib");
  }
}

var lib = ffi.Library(filePath, {
  "funcA": ["int", ["char *"]]
});
```
Path structure:
```
|-- lib/
|   |-- dll/
|   |   |-- 32/
|   |   `-- 64/
|   |-- so/
|   |   |-- 32/
|   |   `-- 64/
|   `-- app.js
|-- node_modules/
|   `-- nofe-ffi/
```

**Comment by TooTallNate** [comment]
`libm` isn't available on windows. Most of the relevant functions, or equivalent/variants of the unix versions, can all be found in the `msvcrt.dll` DLL file.
