### ISSUE TITLE
"Dynamic Symbol Retrieval Error" using rust dll file under windows

### ISSUE THREAD

**Issue by fuyingfuying** [node-ffi/node-ffi#209]
Hi，
I'm a new user of ffi. I'm learning rust language recently. So firstly I read "The Rust Programming Language" eBook from its official website. In the meantime I want use nodejs libs to develop my app because there are no useful rust libs for web development. So I still use nodejs. But there are some heavy computation in my apps, So in these parts i want to use rust instead.  fortunately, In the section 3.3(https://doc.rust-lang.org/stable/book/rust-inside-other-languages.html), they introduce the ffi module can support my idea. So I followed the introduce of section 3.3 to validate this method. However, running the example always generates the following message: 
![image](https://cloud.githubusercontent.com/assets/12774287/8019532/3d82deba-0c86-11e5-8b31-8a1d14ff4132.png)

My environment is windows 8.1 64bits. io.js x64 2.2.1, ffi 1.3.1, rust 1.0.0. the rust example code is:

use std::thread;

fn process() {
    let handles: Vec<_> = (0..10).map(|_| {
        thread::spawn(|| {
            let mut _x = 0;
            for _ in (0..5000001) {
                _x += 1
            }
        })
    }).collect();

    for h in handles {
        h.join().ok().expect("Could not join a thread!");
    }
}

it is same with the The Rust Programming Language ebook. And the node.js code is same with the ebook:

var ffi = require('ffi');

var lib = ffi.Library('target/release/embed', {
  'process': [ 'void', []  ]
});

lib.process();

console.log("done!");

The dll file generated by the rust source file is called "embed.dll". It is generated by the command "cargo build --release".

I want your's solution as quick as posiible, thank you very much!!

**Comment by fuyingfuying** [comment]
Oh, my machine has installed vs 2013 update 4, so the node-gyp works well and the ffi module has installed successfully.

**Comment by unbornchikken** [comment]
http://bluishcoder.co.nz/2013/08/08/linking_and_calling_rust_functions_from_c.html

I think you've missed [no_mangle].

**Comment by fuyingfuying** [comment]
The problem has been solved!!Thank you very much^_^
