### ISSUE TITLE
Could this module be used to bind to an ActiveX component?

### ISSUE THREAD

**Issue by AleCaste** [node-ffi/node-ffi#210]
Hello, I read in stackoverflow that this module could indeed be used to bind to an ActiveX component but I could not find any examples anywhere that would show me how.
I have an "XXXXXX.application" ActiveX control that I would like to use within node but I am totally stuck.
Apparently the way is to connect to the Win32 api through your module and then call CoCreateInstance but I have no idea how to properly do this.
Thanks in advace

**Comment by unbornchikken** [comment]
It will be really hard if not impossible to invoke COM with node-ffi. You can ivoke CoCreateInstance but you gota know proc addresses relative to instance address, which involves some heavy magic like crunching around C++'s vtable.

I would go with [Edge.js](http://tjanczuk.github.io/edge/#/) instead.

**Comment by AleCaste** [comment]
Thanks a lot for your quick response. We'll have a look at Edge then. The only thing is that Edge requires to install a lot more components on Windows machines. But seems to be really powerful.
Thanks again!

**Comment by AleCaste** [comment]
Sorry to bother again.
Apparently the authors of the ActiveX component we want to use have also created a in dll that wraps the activex component to enable the use of this wrapper dll in a .NET environment.
But could we use your module to make use of such a dll from node instead of from a .NET project?
Thanks again

**Comment by unbornchikken** [comment]
.NET dll are not compatile with this module, only native ones with C interface. Edge.js is the only option for this.
