### ISSUE TITLE
Dynamic linking error, C++ compiled DLL file on Windows 8

### ISSUE THREAD

**Issue by dfasdfasf** [node-ffi/node-ffi#212]
I put my dll file in the same directory as my controller but when I try to call the ffi.Library function on the dll I get the module not found dynamic linking error. I checked the directory path with a console log to make sure it was correct. I also tried with and without .dll extension. Heres my code and error message.
![code](https://cloud.githubusercontent.com/assets/13237959/8682601/d6259e28-2a3b-11e5-82c0-6f7d144874a2.PNG)
![error](https://cloud.githubusercontent.com/assets/13237959/8682604/d91f178a-2a3b-11e5-9fb0-8f78d59b041d.PNG)
![directory](https://cloud.githubusercontent.com/assets/13237959/8682615/e4820844-2a3b-11e5-86eb-f85f508d37b8.PNG)

**Comment by TooTallNate** [comment]
Could it be an architecture mismatch? i.e. a 64-bit version of node.js and a 32-bit Dll file?

**Comment by dfasdfasf** [comment]
I am running a 64 bit windows machine, but it is a 64 bit DLL as well.

**Comment by unbornchikken** [comment]
Let's do some sanity checks! What's the output of the following entered in the directory of the script and the dll:

```
node -e console.log(process.arch)
```

and

```
node -e "console.log(require('fs').statSync(require('path').join(__dirname, 'OCTUtil.dll')))"
```

**Comment by dfasdfasf** [comment]
Good Idea, here are the results
![sanitycheck](https://cloud.githubusercontent.com/assets/13237959/8701067/b9eb7d34-2add-11e5-8c3e-71bf7026a0c7.PNG)

**Comment by unbornchikken** [comment]
Ok I believe the issue is that your dll references an other dll that is not accessible in the path. Its confusing because dlopen raising the same error message when the entry dll is missing. I had exactly this issue a few weeks ago.

**Comment by TooTallNate** [comment]
@unbornchikken random side note: you can use the `-p`node flag to avoid the `console.log()` part.

**Comment by dfasdfasf** [comment]
This may sound like a weird question, Im a Javascript developer and working with DLLs is pretty new to me. How can I determine if it is referencing other DLLs? Thanks

**Comment by unbornchikken** [comment]
[Dependency Walker](http://www.dependencywalker.com/)

**Comment by dfasdfasf** [comment]
Problem solved. Thanks
