### ISSUE TITLE
Loading C++ function that returns an openCV matrix

### ISSUE THREAD

**Issue by dfasdfasf** [node-ffi/node-ffi#214]
I am trying to call a function from my C++ compiled DLL library called loadOCTInfo. 

The function specifications are as follows: 
![loadoctinfo](https://cloud.githubusercontent.com/assets/13237959/8806581/53b8bd20-2fa5-11e5-8c9d-26ee6ee10466.PNG)

Heres is the code I have so far. 

`'use strict';

var ffi = require('ffi');
var path = require('path');
var ref = require('ref');
var fileNameStringPtr = ref.refType('string');

var libOCTutil = ffi.Library(path.join(__dirname, 'OCTutil.dll'), {
  'loadOCTInfo': [ 'int', [ filenameStringPtr, 'int' ] ]
});

var output = libOCTutil.loadOCTInfo('examplefilename');

console.log('Your output: ' + output);`

My question is, how do I specify an openCV matrix as my return type. Will I have to wrap the OpenCV matrix return in a C struct?

**Comment by unbornchikken** [comment]
This module only can handle C interfaces, and doesn't have support C structures by value. I suggest that you should only accept and return pointers. If those points to a C struct, then you can acces its members by using ref-struct module.
