### ISSUE TITLE
NAN 2.0 and io.js 3.0 support

### ISSUE THREAD

**Issue by unbornchikken** [node-ffi/node-ffi#219]
I'm in progress on implementing NAN 2.0 support. I've made progress, current version works with Node.js and io.js 1
x, however it has failing tests on io.js 2.x. Later today I'm gonna begin a PR, where anyone can help me out with this, because I'm low on spare time right now.

**Comment by unbornchikken** [comment]
https://github.com/node-ffi/node-ffi/pull/221

**Comment by unbornchikken** [comment]
fyi: it's blocked because of the issues of nan 2.0 https://github.com/nodejs/nan/issues/389

**Comment by antoinepairet** [comment]
@unbornchikken A fix has landed in nan master branch: https://github.com/nodejs/nan/commit/98d38c182e30dd9dae2f8568996fb334e0ddcefc

**Comment by unbornchikken** [comment]
Yeah, I know. I've already finished that PR, but unfortunately it still fails to install on io.js 3.x, because ref module's nan 2.0 support is needed.

**Comment by unbornchikken** [comment]
I did NAN 2.0 PR for ref today: https://github.com/TooTallNate/ref/pull/33 I hope that @TooTallNate is gonna merge that soon.

**Comment by sdepold** [comment]
@unbornchikken PR was merged :)

**Comment by unbornchikken** [comment]
Yeah, merged, but unfortunattelly it segfaults on io.js 3.0.1. We didn't have time to test it on the just released 3.0.2, though. So we're waiting for that PR gets released instead of merged. :)

**Comment by unbornchikken** [comment]
So, it almost done, but unfortunattely we've an issue with an other dependency: https://github.com/TooTallNate/ref-struct/issues/18 We gotta wait for that fixed in order to release io.js 3+ support.

**Comment by rosen-vladimirov** [comment]
Hi all, I've noticed that everything is merged in v2 branch, when can we expect the 2.x version of ffi ?
