### ISSUE TITLE
build error with 1.3.2 (npm install ffi)

### ISSUE THREAD

**Issue by naderalbes** [node-ffi/node-ffi#220]
```
iMac:slotsserver-v2 andrijablazevic$ node -v
v0.12.7
iMac:slotsserver-v2 andrijablazevic$ npm -v
2.11.3
iMac:slotsserver-v2 andrijablazevic$ make --version
GNU Make 3.81
iMac:slotsserver-v2 andrijablazevic$ gcc --version
gcc (Homebrew gcc 5.2.0) 5.2.0
```

```
iMac:slotsserver-v2 andrijablazevic$ npm install ffi

    ref@1.0.2 install /Users/andrijablazevic/Documents/luxslots/slotsserver-v2/node_modules/ffi/node_modules/ref
    node-gyp rebuild

CXX(target) Release/obj.target/binding/src/binding.o
SOLINK_MODULE(target) Release/binding.node

    ffi@1.3.2 install /Users/andrijablazevic/Documents/luxslots/slotsserver-v2/node_modules/ffi
    node-gyp rebuild

CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function 'classify_argument':
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an 'else' statement [-Wempty-body]
FFI_ASSERT (0);
^
CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
LIBTOOL-STATIC Release/libffi.a
CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
cc1plus: error: argument to '-O' should be a non-negative integer, 'g', 's' or 'fast'
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack at ChildProcess.emit (events.js:110:17)
gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andrijablazevic/Documents/luxslots/slotsserver-v2/node_modules/ffi
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "ffi"
npm ERR! node v0.12.7
npm ERR! npm v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! ffi@1.3.2 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@1.3.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls ffi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /Users/andrijablazevic/Documents/luxslots/slotsserver-v2/npm-debug.log
```

**Comment by unbornchikken** [comment]
It looks like a gyp issue:

```
cc1plus: error: argument to '-O' should be a non-negative integer, 'g', 's' or 'fast'
```

Maybe gcc 5.2 has some incompatible argument changes. @TooTallNate what do you you think?

**Comment by naderalbes** [comment]
i try to install on ubuntu also and get this errors and warnings:

slotsdev@lvps87-230-19-125:~/slotsserver-v2$ node -v
v0.12.7
slotsdev@lvps87-230-19-125:~/slotsserver-v2$ npm -v
2.11.3
slotsdev@lvps87-230-19-125:~/slotsserver-v2$ gcc --version
gcc (Ubuntu 4.9.2-0ubuntu1~12.04) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

slotsdev@lvps87-230-19-125:~/slotsserver-v2$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
slotsdev@lvps87-230-19-125:~/slotsserver-v2$ npm install ffi
-
> ref@1.0.2 install /home/slotsdev/slotsserver-v2/node_modules/ffi/node_modules/ref
> node-gyp rebuild

make: Entering directory `/home/slotsdev/slotsserver-v2/node_modules/ffi/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory `/home/slotsdev/slotsserver-v2/node_modules/ffi/node_modules/ref/build'

> ffi@1.3.2 install /home/slotsdev/slotsserver-v2/node_modules/ffi
> node-gyp rebuild

make: Entering directory `/home/slotsdev/slotsserver-v2/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
../deps/libffi/src/closures.c: In function 'dlmmap_locked':
../deps/libffi/src/closures.c:421:7: warning: ignoring return value of 'ftruncate', declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
       ^
../deps/libffi/src/closures.c:433:7: warning: ignoring return value of 'ftruncate', declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
       ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function 'classify_argument':
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an 'else' statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
In file included from ../src/callback_info.cc:8:0:
../src/callback_info.cc: In static member function 'static void CallbackInfo::Callback(const v8::FunctionCallbackInfo<v8::Value>&)':
../src/ffi.h:25:72: warning: 'void NanThrowError(const char*, int)' is deprecated (declared at ../node_modules/nan/nan.h:741) [-Wdeprecated-declarations]
 #define THROW_ERROR_EXCEPTION_WITH_STATUS_CODE(x, y) NanThrowError(x, y)
                                                                        ^
../src/callback_info.cc:151:12: note: in expansion of macro 'THROW_ERROR_EXCEPTION_WITH_STATUS_CODE'
     return THROW_ERROR_EXCEPTION_WITH_STATUS_CODE("ffi_prep_closure() Returned Error", status);
            ^
  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
  SOLINK_MODULE(target) Release/obj.target/ffi_bindings.node
  COPY Release/ffi_bindings.node
make: Leaving directory `/home/slotsdev/slotsserver-v2/node_modules/ffi/build'
ffi@1.3.2 node_modules/ffi
├── bindings@1.2.1
├── ref-struct@1.0.1
├── debug@2.2.0 (ms@0.7.1)
├── nan@1.9.0
└── ref@1.0.2 (nan@1.8.4)
slotsdev@lvps87-230-19-125:~/slotsserver-v2$

**Comment by unbornchikken** [comment]
Yes, there are warnings, but it compiles without errors, so it's good.

**Comment by naderalbes** [comment]
@unbornchikken what you think about compile error on mac ?

**Comment by unbornchikken** [comment]
I've already gave my thoughs on the. I think it's because of gyp is not handling gcc 5.2 properly. @TooTallNate is the right person to say something more accurate on this.

**Comment by naderalbes** [comment]
ok thank you @unbornchikken

**Comment by unbornchikken** [comment]
Would you try ffi@2.0 with io.js@latest?

**Comment by naderalbes** [comment]
i try with node.js last version it works thanks
