### ISSUE TITLE
return char* can not show correct when the return value is Unicode encode 

### ISSUE THREAD

**Issue by siweilvxing** [node-ffi/node-ffi#228]
the function is  

``` c
char* __stdcall DC_i_d_query_name  ( long  IdHandle  )
```

so i use ffi to export it:

``` js
ffi.Library('Trf32.dll',{
		'DC_i_d_query_name':
		['string',['long']],
                'DC_i_d_query_birth':
		['string',['long']]
}
```

then call it in javascript

but when the return value are chinese characters, it shows uncorrect
and when the return value are number characters, it shows correct

**Comment by TooTallNate** [comment]
The "string" type assumes UTF8. If you need to use a different encoding, you'll have to write a custom "Type". See [`ref-wchar`](https://github.com/TooTallNate/ref-wchar) for an example.
