### ISSUE TITLE
Problem with ulong_long

### ISSUE THREAD

**Issue by kimtn-bitmark** [node-ffi/node-ffi#230]
I have 64-bit unsigned integer as a input param in my C function. I try to define wrap interface as bellow

```
var libencrypt = ffi.Library('./mylib', {
  'myfunction': ['void', ['ulong_long']],
})
```
I got this error when i trying to run test

```
assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: could not determine a proper "type" from: "ulong_long"
```
does it have mean sense with you?

**Comment by unbornchikken** [comment]
There is no type 'ulong_long'. See: https://github.com/TooTallNate/ref/wiki/Known-%22types%22

**Comment by TooTallNate** [comment]
Use "ulonglong" or "uint64"

**Comment by kimtn-bitmark** [comment]
:+1:
