### ISSUE TITLE
cannot install locally on my osx

### ISSUE THREAD

**Issue by yorkie** [node-ffi/node-ffi#233]
I just did:

```sh
$ git clone git@github.com:node-ffi/node-ffi.git
$ cd node-ffi && npm install
```

Then the result:

```
ld: library not found for -lgcc_s.10.5
```

BTW, I have installed the Xcode either.

**Comment by unbornchikken** [comment]
You gotta have the proper Xcode Commanline Tools.

**Comment by yorkie** [comment]
But I have installed the Xcode, and found the libgcc_s.10.5 either.
