### ISSUE TITLE
Crash when node-ffi 2.0 is required inside electron

### ISSUE THREAD

**Issue by rosen-vladimirov** [node-ffi/node-ffi#236]
Hi,
We are having a complicated issue, related to both `node-ffi` and `electron`. Let me explain the full details of the problem and I'll be glad if you can advise us how to proceed in this situation.

We are using `node-ffi` in one of our libraries. Now we are working on integration of this library inside electron application. Electron itself is using a fork of iojs and they apply some fixes in order to keep it working in the same way.
After some hard time of debugging, we've found that in latest electron versions, when we call `require(ffi)` the electron crashes. The problem is caused by [one commit](https://github.com/atom/node/commit/205b013ac86e5500678a791cd54f305580fa4f4b) in their fork of `iojs`. I've logged a new issue in electron, explaining the whole situation, and they explained why they need this commit:
```
We do need this commit for embedded blink allocator in node's buffer. Because iojs reimplements node buffer in v3.0, and it starts to manage the memory of buffer, which conflicts with Blink's behavior.
It will cause electron to crash if we remove this commit.
```
You can check the whole discussion in the **[electron issue](https://github.com/atom/electron/issues/2680)** and the callstack of the error is:
```
0   ffi_bindings.node               0x0000000110491fba ffi_prep_cif_core + 61
1   ffi_bindings.node               0x000000011049211a ffi_prep_cif + 23
2   ffi_bindings.node               0x000000011048ff93 FFI::FFIPrepCif(Nan::FunctionCallbackInfo<v8::Value> const&) + 469
3   ffi_bindings.node               0x0000000110490a18 Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) + 131
4   libnode.dylib                   0x000000010b15b0bf v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) + 159
5   libnode.dylib                   0x000000010b17fa85 0x10ade2000 + 3791493
...
```
So the guys from electron explained that currently it is not possible to remove the commit, which breaks `node-ffi`. Maybe you can suggest a workaround that we can apply in our node-ffi fork in order to be able to use your library inside electron.

You can use **[this application](https://github.com/rosen-vladimirov/myElectronApp)** as a sample reproduction case. Just execute the follow the steps below:
* `npm i -g electron-prebuilt` - make sure to check the installed version as you'll need it later.
* `git clone https://github.com/rosen-vladimirov/myElectronApp`
* `cd myElectronApp`
* `./installAndStart.sh 0.31.2 x64` - here you can replace 0.31.2 with the version of electron-prebuilt that you have installed.
This script will install the required dependencies, rebuild them with correct headers (electron requires special way of rebuilding) and start the app. You will not see anything first time you start it, as electron will crash. After that, just remove `ffi = require("ffi") ` from `main.js` file and execute `electron .` You'll see that the app will start.

I know that your latest version is working fine with iojs 3.x, but we need it to work with electron as well. We'll be really happy in case you have time to take a look at this issue and suggest any possible solutions/workarounds.

Thanks in advance for your help and understanding!

**Comment by unbornchikken** [comment]
We're aware of this issue. If you try node-ffi with io.js 3.0 or with 3.1 then it will crash too. That's because of an alignment issue of that commit above. We cannot do anything about it, it lies in that buffer implementation not in ffi side. Issue history and the fix is there: https://github.com/nodejs/node/issues/2484#issuecomment-133563531

Electron guys should integrate that mentioned commit too.

**Comment by rosen-vladimirov** [comment]
Hi @unbornchikken, 
Thank you for the information and please excuse me for the late reply. Electron guys have found a way to fix this issue. However we are trying to use node-ffi with iojs 3.3.0 on our side and we have a lot of troubles with the garbage collection. I'll open separate issue for it.
Thank you, your help is really appreciated!
