### ISSUE TITLE
C++ LoadLibrary fails when load dll which generated by vs2010

### ISSUE THREAD

**Issue by topwood** [node-ffi/node-ffi#237]
Firstly, I have a **add.dll** which generated by vs2010 IDE,

add.h:

    #define _EXPORT
    #ifndef _EXPORT
    #define EXPORT __declspec(dllimport)
    #else
    #define EXPORT __declspec(dllexport)
    #endif
    EXPORT int add(int a,int b);

add.c:

    #include "add.h"

    int add(int a,int b) {
  
      return a+b;
    }

And then ,i want to call this add.dll in my another **pdf.c** program: 

    #include "add.h"
    #include <windows.h>
    #define _EXPORT
    // #pragma comment(lib,"add.lib")
    // __declspec(dllimport) int add(int a,int b);
    typedef int (*DLLFUN)(int a, int b);

    DLLFUN fun;

    EXPORT int dosome(int a,int b) {
	HMODULE hdll = LoadLibrary("add.dll");
	if(hdll!=NULL){
		// DLLFUN add = NULL;
		fun=(DLLFUN)GetProcAddress(hdll,"add"); //----here find the add fun
		
		return fun(a,b);
	}
	return 0;
  
}
And i build and link this pdf.c with vs2010 tools but not vs2010 IDE itself:

    cl.exe /D_USRDLL /D_WINDLL C:\Users\liz\Desktop\pdfdll\Release\pdf.c /link /DLL /OUT:C:\Users\liz\Desktop\pdfdll\Release\pdf.dll

Then a get a **pdf.dll** which i want to call it using **node-ffi** with node.js:

    var ffi = require('ffi');
    var ref = require('ref');

    var intPtr = ref.refType(ref.types.int);

    var libm = ffi.Library(__dirname+'\\pdf.dll', {
    'dosome': [ 'int', [ 'int','int' ] ]
    });

    var a = libm.dosome(1,5); 
    console.log(a);

As a result, the console.log output 0 which meaning in pdf.c program ,it fails to load the add.dll library.

But what is strange that when i build and link the add.c and add.h using vs2010 tool like above, it print the right answer 6.

So, i have tried to find what this two methods different. I use the **Dependency Walker** to find that the dll build with vs2010 IDE dependent with **MSVCR100.DLL** and **KERNEL32.DLL** while the dll build with cl.exe only dependent with **KERNEL32.DLL**.

In the real situation, i have a more complexer porgram which export a dll and a .h file using VS2010 IDE. I have to do some work to call this dll in my node.js program. Where am i wrong and what can I do ?

actually, when i call the dll which was generated by vs2010 IDE, node-ffi will throw **dynamic linking err**.

machine: win7 64      VS2010

**Comment by unbornchikken** [comment]
This question should go to the corresponding MSDN forum, because ffi loads your library well, there is nothing to be fixed here.

**Comment by topwood** [comment]
actually, when i call the dll which was generated by vs2010 IDE, node-ffi will throw dynamic linking err.
the only way i call dll using node-ffi is building the dll like 
    cl.exe /D_USRDLL /D_WINDLL C:\Users\liz\Desktop\pdfdll\Release\pdf.c /link /DLL /OUT:C:\Users\liz\Desktop\pdfdll\Release\pdf.dll ??

**Comment by unbornchikken** [comment]
Ok, but thats another issue. Could you please put the error there that ffi throws?

**Comment by topwood** [comment]
C:\Users\liz\Desktop\pdfdll\Release>node test.js

C:\Users\liz\Desktop\pdfdll\Release\node_modules\ffi\lib\dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
          ^
Error: Dynamic Linking Error: "C:\Users\liz\Desktop\pdfdll\Release\add2.dll":
    at new DynamicLibrary (C:\Users\liz\Desktop\pdfdll\Release\node_modules\ffi\
lib\dynamic_library.js:74:11)
    at Object.Library (C:\Users\liz\Desktop\pdfdll\Release\node_modules\ffi\lib\
library.js:45:12)
    at Object.<anonymous> (C:\Users\liz\Desktop\pdfdll\Release\test.js:7:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

i have read other dynamic issues, but i cant find any solutions

**Comment by unbornchikken** [comment]
What output `set DEBUG=ffi:*&&node test.js` gives?

**Comment by topwood** [comment]
ffi:DynamicLibrary new DynamicLibrary() +3ms msvcrt.dll undefined
 ffi:_ForeignFunction invoking proxy function +1ms
 ffi:DynamicLibrary dlsym() +4ms _errno

**Comment by unbornchikken** [comment]
The error is that your DLL is links CRT dynamically but msvcrt.dll is not found in the path. You should link CRT statically.

**Comment by topwood** [comment]
the msvcrt.dll is in my C:\Windows\System32 path..

**Comment by unbornchikken** [comment]
You should link CRT statically in a node module anyway.

**Comment by topwood** [comment]
thank you very much! but how to link statically in node module..use ffi.DynamicLibrary()?

**Comment by unbornchikken** [comment]
It's a comipler feature not an ffi one: https://msdn.microsoft.com/en-us/library/abx4dbyh.aspx

**Comment by topwood** [comment]
thank you very much!

**Comment by yuzhaodong** [comment]
i guess your nw.js is x64，you can try nw.js x86，i successed with nw.js x86

**Comment by xiaozhu20170310** [comment]
Hi, I meet the same problem . Did you successed?
win10 x64 vs2015 node x64 nw 64bit
dll 64bit
the error is:
Uncaught Error: Dynamic Linking Error: Win32 error 193
    at new DynamicLibrary (F:\桌面\nwc1\node_modules\ffi\lib\dynamic_library.js:74:11)
    at Object.Library (F:\桌面\nwc1\node_modules\ffi\lib\library.js:45:12)

**Comment by topwood** [comment]
hello, i have solved this problem in my win7 computer.好像当初用VS建的工程有问题，建个64位的就搞定了，具体的忘了

**Comment by topwood** [comment]
具体的忘了，好像当初用VS建工程用了32位的，所以用VS一直不行，后来改下工程的配置，用64位的就好了。好像是这个原因。 @xiaozhu20170310

**Comment by xiaozhu20170310** [comment]
奥，不会c++，64位dll是别人帮忙生成的

**Comment by topwood** [comment]
我也不会，但是我告诉他们C++的该怎么做，最后可以了 @xiaozhu20170310

**Comment by xiaozhu20170310** [comment]
好的，谢谢，我试试！
