### ISSUE TITLE
Incorrect example in README.md

### ISSUE THREAD

**Issue by unrealsolver** [node-ffi/node-ffi#240]
I tried import library as `ffi`, however it produced an error. Than I tried `node-ffi` which works correctly,

**Comment by TooTallNate** [comment]
Not sure what you mean. Can you explain in some more detail?

**Comment by unrealsolver** [comment]
Sure. Does not work:
```
var ffi = require('ffi')
```
Works for me:
```
var ffi = require('node-ffi')
```
I found it here: https://github.com/node-ffi/node-ffi/blob/master/README.md#example

**Comment by unbornchikken** [comment]
You gotta install ffi by

```bash
npm install ffi --save
```

instead of 

```bash
npm install node-ffi --save
```

The latter installs a deprecated version.

**Comment by unrealsolver** [comment]
Project name and package name are different - it made me confused.
Thanks.
