### ISSUE TITLE
npm install fails on Linux for Node 4.0/4.1 and iojs v3.3.1

### ISSUE THREAD

**Issue by 6D65** [node-ffi/node-ffi#245]
Hi,

Seems like latest versions of nodejs and iojs are not supported even though there is a closed issue mentioning the support for Node 4.0.

I've tried deleting the node-gyp folder mentioned in the error message. Still nothing works. There's no local node_modules folder in the project that could cause this issue.

```bash
rm -rf /home/user/.node-gyp
```

The full error output can be seen here (https://gist.github.com/6D65/d3efadef2b9acec20a28)

Am I missing something?
Thank you.

**Comment by gwicke** [comment]
FWIW, master does compile for me.

```
"ffi": "git+https://github.com/node-ffi/node-ffi.git"
```

@TooTallNate, anything blocking a new release?

**Comment by unbornchikken** [comment]
See https://github.com/node-ffi/node-ffi/issues/262
