### ISSUE TITLE
How To: Callbacks and Proper Parameter Passing

### ISSUE THREAD

**Issue by tysenmoore-xse** [node-ffi/node-ffi#246]
I apologize up front, I am still new to web programming but I have a few questions regarding the proper use of callbacks and passing of correct data types when the interface using `void*` within ffi.

I ran a simple example opening libc and got strlen and stcmp to work fine.  I wanted to extend my understanding to something more challenging that contained `void*` and callbacks.  I chose to test `qsort` from libc.  I tried a number of things and looked all over trying to piece together the correct solution but I can't get the right combination.  Some syntax I found for ffi/ref examples may be out of date or not (pointer, etc), so I'm not clear what a working solution would look like.  Any help/suggestions would be MUCH appreciated.

       var ffi   = require('ffi');
       var ref   = require('ref');
       var array = require('ref-array');

       var libName = "/lib/x86_64-linux-gnu/libc.so.6";

       // This works fine...
       var libc = ffi.Library( libName, { 'strlen': ['size_t',['string']],
                                          'strcmp': ['int',['string', 'string']] });

        var lstData  = ['l','m','e'];
        var strArray = array('string', 3);
        var lst = new strArray( lstData );

        var qsortCompare = ffi.Callback('int', ['string', 'string'], 
                                        function(p1,p2) {
                                console.log("   >>>> "+p1+" ? "+p2);
                                return libc.strcmp(p1,p2);  // previously loaded strcmp for testing purposes
                                });

        var libcq = ffi.Library( libName, { 'qsort': ['void',[strArray,'size_t','size_t',qsortCompare]] });

        console.log("PRE-SORT: "+lst);
        libcq.qsort( lst, lst.length, 4, qsortCompare ); // 4 == sizeof(char*)?
        console.log("POST-SORT: "+lst);

For quick reference, the qsort interface looks like this:

        void qsort(void *base, 
                  size_t nmemb, 
                  size_t size,
                   int (*compar)(const void *, const void *));

When I run it I get:

    "AssertionError: could not determine a proper "type" from: {"type":"Buffer","data":[73,187,254,107,156,121,2,127]}

From what I can tell it is not happy with the first parameter `strArray`, but I could be wrong about that as well.

**Comment by TooTallNate** [comment]
Look into using the `ffi.Function` as the "type", rather than the `ffi.Callback` instance. Ping back here if you still get stuck.

**Comment by tysenmoore-xse** [comment]
Thanks for the suggestion and fast response.  Your suggestion got me much closer.  After modifying the code I get a callback but get unexpected results and not sure the `strArray` is updated as it should.

Current code snippet:

       var lstData  = ['l','m','e'];
       var strArray = array('string', 3);
       var lst = new strArray( lstData );

       var qsortCompare = ffi.Function('int', ['string', 'string']);

        var libcq = ffi.Library( libName, { 'qsort':
                                 ['void',
                                 [strArray,'size_t','size_t',qsortCompare]] });

        console.log("PRE-SORT: "+lst);
        libcq.qsort( lst, lst.length, 4, 
                     function(p1,p2) {
                                        console.log("  str: >>>> "+p1+" ? "+p2);
                                        return libc.strcmp(p1,p2);
                                     }); // 4 == sizeof(char*)?
        console.log("POST-SORT: "+lst);

The output is:

    "PRE-SORT: l,m,e"
    "  str: >>>>  ? m"
    "  str: >>>> l ? "
    "  str: >>>> l ? m"
    "POST-SORT: l,m,e"

The same [basic] program in C yields:

    PRE-SORT:l,m,e
        str:  >>>> m ? e
        str: >>>> l ? e
        str: >>>> l ? m
    POST-SORT:e,l,m

* Could the signature be incorrect since I define it as `string,string`, but the interface is `void*,void*`?
* Also, the first argument to qsort is `void*`, I've defined it as `strArray`, is this OK?  Should I pass a reference to ensure I get the result back?

**Comment by TooTallNate** [comment]
Here's an example that I got working:

``` js
var ffi = require('ffi');
var ArrayType = require('ref-array');

var IntArray = ArrayType('int');
var Comparator = ffi.Function('int', [ 'void *', 'void *' ]);

var libc = ffi.Library('libc', {
  qsort: [ 'void', [ 'void *', 'size_t', 'size_t', Comparator ] ]
});

function cmpfunc (aPtr, bPtr) {
  // cast aPtr and bPtr to "int *" type
  aPtr = aPtr.reinterpret(IntArray.BYTES_PER_ELEMENT);
  aPtr.type = 'int';
  bPtr = bPtr.reinterpret(IntArray.BYTES_PER_ELEMENT);
  bPtr.type = 'int';

  // get raw Number values from int pointers
  var a = aPtr.deref();
  var b = bPtr.deref();

  // numerical sort
  return a - b;
}

var values = new IntArray([ 88, 56, 100, 2, 25 ]);

console.log("Before sorting the list is:");
console.log(values);

libc.qsort(values.buffer, values.length, IntArray.BYTES_PER_ELEMENT, cmpfunc);

console.log("After sorting the list is:");
console.log(values);
```

**Comment by TooTallNate** [comment]
^ To note:

 * Passing `values.buffer` in as the "array" isn't great... ideally it would be simply `values`, but currently that doesn't work since we're setting "void *" as the argument type (it doesn't know how to handle regular Objects as opposed to Buffer instances).
 * If you were to pass `IntArray` as the argument type instead of "void *", then passing in `values` directly works as expects, but then the binding function only works with "int" arrays. I consider this a bug/API flaw that I would like to fix at some point.

**Comment by tysenmoore-xse** [comment]
Thanks so much for the example.  I was able to refactor your example to work with strings as well.  It really helps kick start my understanding.  I need to think more in terms of C, I was trying to cut corners.  I think I have a much better understanding.  Thanks again!

**Comment by tysenmoore-xse** [comment]
Found another issue with this solution--likely me but not sure what is going on.  I took this example and put it in a simple Angular controller and trigger the code from a button.  However, this time instead of passing in `cmpFunc` I use  `this.ext_cmpFunc` which is a member of my controller.

So basically something like this:

    var app = angular.module('App', []);
    app.controller('Ctrl', [ '$scope',  function($scope) {

    this.sanity = "working";

    this.ext_cmpfunc = function( aPtr, bPtr ) {
        console.log( "this = "+this );
        console.log( "this.sanity = "+this.sanity );

        var IntArray = ArrayType('int');

        // cast aPtr and bPtr to "int *" type
        aPtr = aPtr.reinterpret(IntArray.BYTES_PER_ELEMENT);
        aPtr.type = 'int';
        bPtr = bPtr.reinterpret(IntArray.BYTES_PER_ELEMENT);
        bPtr.type = 'int';

        // get raw Number values from int pointers
        var a = aPtr.deref();
        var b = bPtr.deref();

        // numerical sort
        return a - b;
    };

    this.buttonHandler = function() {
        console.log( "this = "+this );
        console.log( "this.sanity = "+this.sanity );

        var IntArray = ArrayType('int');
        var Comparator = ffi.Function('int', [ 'void *', 'void *' ]);

        var libc = ffi.Library('libc', {
          qsort: [ 'void', [ 'void *', 'size_t', 'size_t', Comparator ] ]
        });

        var values = new IntArray([ 88, 56, 100, 2, 25 ]);

        console.log("Before sorting the list is:");
        console.log(values);
                                                                                                                      
        libc.qsort(values.buffer, values.length, IntArray.BYTES_PER_ELEMENT, this.ext_cmpfunc);

        console.log("After sorting the list is:");
        console.log(values);
    };
    }]);

Now if I run this, the `this` logging in the `buttonHandler` shows:

    this = [object Object]
    this.sanity = working

When the callback is called I get very different results:

    this = [object Window]
    this.sanity = undefined

I am new to much of this but is this expected behavior from an ffi callback in this scenario?  Is there a way to correct the problem so `this` is scoped within the callback?  Thanks again for the time and support.

**Comment by TooTallNate** [comment]
Look into using [`Function#bind()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) on the `ext_cmpfunc` when passing it in to qsort (in short, do `this.ext_cmpfunc.bind(this)`.

**Comment by tysenmoore-xse** [comment]
Works like a champ!  Thanks so much!
