### ISSUE TITLE
How to: Array of Structs as an Out Parameter

### ISSUE THREAD

**Issue by tysenmoore-xse** [node-ffi/node-ffi#247]
I have a situation where I call an API and in returns an array of structures.  I have tried two basic approaches: an array of structs and another `struct***`.  I have found that the `struct***` gets me the closest but doesn't entirely work, nor do I know how to iterrate the array--without manually iterating the array as I have read some people do.  What is the correct/preferred approach to support an out parameter for an array of structs.  I've looked online but I didn't see a good reference for out parameters with an array of structs.

So far I have:  (`struct***` implementation):

    var ffi        = require('ffi');
    var ref        = require('ref');
    var ArrayType  = require('ref-array');
    var StructType = require('ref-struct');

    var deviceInfo = StructType({
            serNum: ArrayType("uint8", 32),
            hwVersion: "uint8",
            swVersion: "uint32"
        });

    var device = StructType({
            
            usbDev: "void *",
            usbDevHnd: "void *",

            devInfo: deviceInfo,
            //...
        });

    // Some basic types
    var uint16Ptr     = ref.refType('uint16');
    var context       = ref.types.void;
    var contextPtr    = ref.refType(context);
    
    var devicePtr       = ref.refType(device);
    var devicePtrPtr    = ref.refType(devicePtr);
    var devicePtrPtrPtr = ref.refType(devicePtrPtr);

    var libName = "/home/swdev/sdk/linux/libsdk.so";
    var lib = ffi.Library( libName, {
        //... 
        // C API:
        // uint32 platformGetDeviceList( struct context*   ctx,
        //                               uint16*           nDevices,
        //                               struct device***  devices );
        'platformGetDeviceList': [ 'uint32', [contextPtr, uint16Ptr, devicePtrPtrPtr]] });
    //...
    var nDevices   = ref.alloc('uint16'); // out param
    var deviceList = ref.alloc(anlzr_DevicePtrPtr);

    ret = lib.platformGetDeviceList( ctxPtr,       // IN
                                     nDevices,     // OUT
                                     deviceList ); // OUT

    var nDevices = nDevices.deref();   // Grab the actual value
    console.log("Devices: "+nDevices); // Works fine

I have left out some other init code to make it easier to follow.  I have verified in my SDK dll that the function is called and `ctxPtr`/`nDevices` are correct.  Also the function executes correctly.  Currently my difficulty is trying to get `deviceList` returned properly and then iterate it.  I get close with:

    var realdeviceList = deviceList.deref();
    console.log("realdeviceList: "+realdeviceList);

    var realdevice     = realdeviceList.deref();  // assuming list[0]
    console.log("realdevice: "+realdevice);

    var devInfo        = realdevice.devInfo;
    console.log("Devices.dev: "+devInfo);

The reason I say "it is close" is because the dump of `realdevice` (below) has the correct `devInfo.serNum` within the bowels of the data (`64281301010203`).  However when I try to get at the data it doesn't work ("Devices.dev: undefined")

    "Devices: 1"
    "realdeviceList: ??%="
    "realdevice: ???%=64281301010203	?%="
    "Devices.dev: undefined"

If I modify the code slightly to attempt to use an array of structs I get all zeros.

    var deviceArray = ArrayType(device, 10); // arbitrary size, actual unknown
    var devicePtr = ref.refType(deviceArray);
    var deviceList = ref.alloc(devicePtr);    

    // call anlzr_platformGetDeviceList() the same as before

    var realdeviceList = deviceList.deref();
    var realdevice     = realdeviceList.deref();
    console.log("realdevice: "+realdevice[0]);

    var devInfo        = realdevice[0].devInfo;
    console.log("Devices.dev: "+devInfo);

Here `devInfo` is not undefined; however, if I reference anything inside of it, it returns all zeros for all the data types.

Do you have any recommendations for an array of structs as an out parameter?  Or possibly see anything blatantly wrong?  Thanks for time and any suggestions.

**Comment by TooTallNate** [comment]
It would probably be easier for me to port over if I could see some example C code that works.

**Comment by tysenmoore-xse** [comment]
The actual code I am interfacing is a proprietary SDK to some proprietary hardware over USB.  Luckily the portion of code I am accessing is a thin shim over libusb.  So I have modified my example from my previous posting to work with libusb directly, this exercises the same code and more importantly the `struct***` as an out parameter.  

The basic parts of the code are to: 
* init libusb
* get a listing of all devices
* loop through them and get some descriptor information about each device.  

As you'll see I have commented out the for loop since this part remains a mystery for me at this point.  The code does try to get the descriptor information on `device[0]`; the call seems successful, but I cannot access the device info in `descr`.

Thanks so much for the time and support, it is much appreciated.

        var libusb_context       = ref.types.void;
        var libusb_contextPtr    = ref.refType(libusb_context);
        var libusb_contextPtrPtr = ref.refType(libusb_contextPtr);

        // struct list_head { struct list_head *prev, *next; };
        var list_head = StructType({
            prev: "void *",
            next: "void *"
        });

        var libusb_device = StructType({
        	lock: "void *",                 // usbi_mutex_t
        	refcnt: "int",                  // int

        	ctx: libusb_contextPtr,         // struct libusb_context*
                                            
        	bus_number: "uint8",            // uint8_t
        	device_address: "uint8",        // uint8_t
        	num_configurations: "uint8",    // uint8_t
        	speed: "uint32",                // enum libusb_speed

        	list: list_head,                // struct list_head
        	session_data: "uint32",         // unsigned long
        	os_priv: ArrayType("uint8", 1)  // unsigned char[0]
        });

        var libusb_device_descriptor = StructType({
            bLength:            "uint8",
            bDescriptorType:    "uint8",
            bcdUSB:             "uint16",
            bDeviceClass:       "uint8",
            bDeviceSubClass:    "uint8",
            bDeviceProtocol:    "uint8",
            bMaxPacketSize0:    "uint8",
            idVendor:           "uint16",
            idProduct:          "uint16",
            bcdDevice:          "uint16",
            iManufacturer:      "uint8",
            iProduct:           "uint8",
            iSerialNumber:      "uint8",
            bNumConfigurations: "uint8"
        });

        var libusb_device_descriptorPtr = ref.refType(libusb_device_descriptor);

        var libusb_devicePtr       = ref.refType(libusb_device);
        var libusb_devicePtrPtr    = ref.refType(libusb_devicePtr);
        var libusb_devicePtrPtrPtr = ref.refType(libusb_devicePtrPtr);

        var libName = "/lib/x86_64-linux-gnu/libusb-1.0.so.0"; // make dynamic later
        var lib = ffi.Library( libName, {
            // int libusb_init(libusb_context **ctx);
            'libusb_init': ["int", [libusb_contextPtrPtr]],

            // ssize_t libusb_get_device_list(  libusb_context *ctx,
            //                                  libusb_device ***list );
            'libusb_get_device_list': [ "int32", [ libusb_contextPtr, 
                                                   libusb_devicePtrPtrPtr ]],

            // int libusb_get_device_descriptor(libusb_device *dev,
            //                          struct libusb_device_descriptor *desc);
            'libusb_get_device_descriptor': [ "int", [ libusb_devicePtr, 
                                              libusb_device_descriptorPtr ]],
        });

        // struct libusb_context* usbCtx;
        // int rc = libusb_init(&ctx->usbCtx);
        var ctxPtrPtr = ref.alloc( libusb_contextPtrPtr );
        var rc        = lib.libusb_init( ctxPtrPtr );

        if (rc != 0) {
            console.log("INIT FAILED: "+rc);
            return;
        }
        console.log("INIT SUCCESS!!!");

        // ssize_t count;
        // libusb_device** usbDevices;
        // count = libusb_get_device_list(ctx->usbCtx, &usbDevices);
        var ctxPtr     = ctxPtrPtr.deref();
        var deviceList = ref.alloc( libusb_devicePtrPtr );
        var count      = lib.libusb_get_device_list( ctxPtr, deviceList );

        if (count <= 0) {
            console.log("libusb_get_device_list FAILED: "+count);
            return;
        }
        console.log("libusb_get_device_list: count: "+count);

        // struct libusb_device_descriptor desc;
        // memset(&desc, 0, sizeof(desc));
        // for ( idx = 0; (idx < count) && ANLZR_SUCCEEDED(result); ++idx )
        // {
        //    rc = libusb_get_device_descriptor(usbDevices[idx], &desc);
        //    ...
        // }

        // for (var device in deviceList) { ????? ULTIMATE GOAL ??????

            var device = deviceList.reinterpret(libusb_device.BYTES_PER_ELEMENT);

            var descr = ref.alloc( libusb_device_descriptor );
            rc = lib.libusb_get_device_descriptor( device, descr );

            if (rc != 0) {
                console.log("INIT FAILED: "+rc);
                return;
            }
            console.log("libusb_get_device_descriptor SUCCESS!!!");

            // These are undefined, yet the call was successful
            console.log( "descr vid:pid: "+descr.idVendor+":"+descr.idProduct );

            // Display VID:PID as hex values
            //var vidHex = ("0000" + descr.idVendor.toString(16)).substr(-16);
            //var pidHex = ("0000" + descr.idProduct.toString(16)).substr(-16);
            //console.log( "descr vid:pid: "+vidHex+":"+pidHex );

        // } // end for loop

        //-------------------------------------------------------
        // NOTE: For the sake of example I am ignoreing the 
        //       libusb_free_device_list().
        //-------------------------------------------------------

**Comment by TooTallNate** [comment]
So what I did was basically port the example from this SO answer: http://stackoverflow.com/a/14722194/376773

The output is virtually identical to that C program (hex formatting is a bit off, but oh well). Please let me know if you have any issues:

``` js
var ffi = require('ffi');
var ref = require('ref');
var assert = require('assert');
var StructType = require('ref-struct');
var ArrayType = require('ref-array');

// typedefs/var libusb_context = ref.types.void;
var libusb_contextPtr = ref.refType(libusb_context);
var libusb_contextPtrPtr = ref.refType(libusb_contextPtr);

var libusb_device = ref.types.void;
var libusb_devicePtr = ref.refType(libusb_device);
var libusb_devicePtrPtr = ref.refType(libusb_devicePtr);
var libusb_devicePtrPtrPtr = ref.refType(libusb_devicePtrPtr);
var libusb_devicePtrArray = ArrayType(libusb_devicePtr);

var libusb_device_descriptor = StructType({
  bLength:            'uint8',
  bDescriptorType:    'uint8',
  bcdUSB:             'uint16',
  bDeviceClass:       'uint8',
  bDeviceSubClass:    'uint8',
  bDeviceProtocol:    'uint8',
  bMaxPacketSize0:    'uint8',
  idVendor:           'uint16',
  idProduct:          'uint16',
  bcdDevice:          'uint16',
  iManufacturer:      'uint8',
  iProduct:           'uint8',
  iSerialNumber:      'uint8',
  bNumConfigurations: 'uint8'
});
var libusb_device_descriptorPtr = ref.refType(libusb_device_descriptor);


// lib definition
var lib = ffi.Library('libusb-1.0', {
  'libusb_init': ['int', [ libusb_contextPtrPtr ]],
  'libusb_get_device_list': [ 'size_t', [ libusb_contextPtr,
                                          libusb_devicePtrPtrPtr ]],
  'libusb_get_device_descriptor': [ 'int', [ libusb_devicePtr,
                                             libusb_device_descriptorPtr ]]
});


// usage
var rc;
var contextPtrPtr = ref.alloc(libusb_contextPtr, null);

rc = lib.libusb_init(contextPtrPtr);
assert(rc == 0);

var contextPtr = contextPtrPtr.deref();

var listPtrPtrPtr = ref.alloc(libusb_devicePtrPtr, null);
var count = lib.libusb_get_device_list(contextPtr, listPtrPtrPtr);
assert(count > 0);

var listPtrPtr = listPtrPtrPtr.deref();

var devices = new libusb_devicePtrArray(listPtrPtr.reinterpret(ref.sizeof.pointer * count));
var desc = new libusb_device_descriptor();

for (var i = 0; i < devices.length; i++) {
  var devicePtr = devices[i];

  // reset struct values to 0
  desc.ref().fill(0);

  rc = lib.libusb_get_device_descriptor(devicePtr, desc.ref());
  assert(rc == 0);

  console.log('Vendor:Device = %s:%s', desc.idVendor.toString(16), desc.idProduct.toString(16));
}
```

**Comment by tysenmoore-xse** [comment]
Thanks so much for the working example.  I apologize for mistaking your original post.  I thought I'd take another stab at the ffi port and also have the C code in comment form.  I suppose just the C code was probably a little easier to deal with.  The SO example you found matched what I was attempting to a tee.  Thanks again.  I really appreciate your time and support, this was an invaluable example of several concepts.
