### ISSUE TITLE
The callback blocks on when passing a non-owned string

### ISSUE THREAD

**Issue by 6D65** [node-ffi/node-ffi#248]
Hi,

I'm trying to call a JS callback from a CLib. Callback gets 2 params, one of them is a string. When i use in C a pointer to a string sent from JS, and call the callback with it, the callback works as expected. When I make a string in C and pass it to the callback it blocks. And nothing happens.

Is this expected? Shall I use a special type when defining the callback?

Thanks

**Comment by 6D65** [comment]
Actually this is not entirely accurate. Will investigate more then reopen the defect.

**Comment by 6D65** [comment]
I haven't got to the bottom of this yet. Though the weird thing, is that the callback pointer is being stored, and from one part of the program it works ok. Then in another part(function) calling the callback just stalls.

**Comment by TooTallNate** [comment]
Do you have some example code to repro the problem?

**Comment by 6D65** [comment]
@TooTallNate  It's complicated. It's a rust library pretending to be a C library. Will try to isolate the issue and write a simple reproducible example then update the defect. Even though the Rust library is working ok with python ffi.

**Comment by 6D65** [comment]
@TooTallNate  actually, if you're curious, here's the strace(for one thread i think) of successfully calling the callback in javascript. With an appropirate console.log at the bottom.
```shell
write(1, "[swiboe_new_rpc] [working_callba"..., 42[swiboe_new_rpc] [working_call
back][call]
) = 42
futex(0x7ff8240008c8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7ff8240008c8, FUTEX_WAKE_PRIVATE, 1) = 1
ioctl(1, SNDCTL_TMR_TIMEBASE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=18, ws_col=80, ws_xpixel=0, ws_ypixel=0}) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
read(3, "*", 1)                         = 1
rt_sigaction(SIGWINCH, {0x9df220, ~[RTMIN RT_1], SA_RESTORER, 0x7ff828853cb0}, N
ULL, 8) = 0
write(4, "*", 1)                        = 1
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0x7ff8240008c8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7ff8240008c8, FUTEX_WAKE_PRIVATE, 1) = 1
write(1, "[JS][Callback][argsString][param"..., 45[JS][Callback][argsString][par
ameter string]
) = 45
futex(0x7ff8240008c8, FUTEX_WAKE_PRIVATE, 1) = 1
```

here's the same exact code(copy pasted) in another function calling the same callback with the same parameters. now it just blocks
```shell
[client::rpc::server::Rpc] [next to the call] [callback][0x00007f1b3fce9010]
NULL, 8) = 0
write(4, "*", 1)                        = 1
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0x7f1b380008c8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f1b380008c8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f1b380008c8, FUTEX_WAKE_PRIVATE, 1) = 1
```

Granted. it's not too much. Will investigate more when i'll have some free time. Thank you for looking at it.
