### ISSUE TITLE
getting this error on window 2008 R2 ,node 0.10.25 , VS 2015  when installing node-ffi

### ISSUE THREAD

**Issue by frndxyz** [node-ffi/node-ffi#252]
Log.....

dlfcn.c
dlfcn.vcxproj -> C:\node_modules\node-ffi\build\Release\dlfcn.lib
test
..\libffi-build.sh: deps/libffi: No such file or directory
c:\sh\make.exe: *** No targets. Stop.
pthread.c
c:\node_modules\node-ffi\deps\pthreads-win32\pthread.h(320): error C2011: 'timespec': 'struct' type redefinition [C:\no
de_modules\node-ffi\build\deps\pthreads-win32\pthread.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\time.h(39): note: see declaration of 'timespec'
gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
67:23)
gyp ERR! stack at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuil
d"
gyp ERR! cwd C:\node_modules\node-ffi
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! node-ffi@0.5.7 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-ffi@0.5.7 install script.
npm ERR! This is most likely a problem with the node-ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls node-ffi
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js"
"install" "node-ffi"
npm ERR! cwd C:\
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! C:\npm-debug.log
npm ERR! not ok code 0

**Comment by unbornchikken** [comment]
The actual module's name is: ffi, so try with:

`npm install ffi`

**Comment by frndxyz** [comment]
yap , thanks
