### ISSUE TITLE
.obj function calling is possible with FFI?

### ISSUE THREAD

**Issue by frndxyz** [node-ffi/node-ffi#253]
i want to call function inside .obj file created by node-gyp compilation. is it possible?

**Comment by TooTallNate** [comment]
Not sure exactly what you mean. What is .obj file?

**Comment by frndxyz** [comment]
when compiling module with node-gyp, it create some .obj files inside \build\Release\obj\ . this files i am talking about.

**Comment by TooTallNate** [comment]
You can link to shared library files. That is, `.dylib` files on OSX, `.dll` files on Windows, `.so` files on basically everywhere else. The `.node` file that node-gyp generates by default it a shared library as well, so you could theoretically link to an exported symbol in the generated `.node` file.

See this .gyp file if you want an example of creating a proper shared library file: https://github.com/TooTallNate/node-dlfcn/blob/master/test/binding.gyp

**Comment by frndxyz** [comment]
got it @TooTallNate
