### ISSUE TITLE
Function call working on nodejs but not electron: how to debug?

### ISSUE THREAD

**Issue by antoinepairet** [node-ffi/node-ffi#255]
I am consuming a DLL through node-ffi both via node and electron. The DLL allows to control another program. All functions but one work great. There is one function that is not working using electron while it works using nodejs. When that particular function is called from a terminal using node it works. However, when called from an electron app, it does not work. No error is thrown. The return code is 0 = everything is OK.

How can I debug this issue?

The goal of that function is to bring the UI of the other program to the top. It takes an integer as argument and returns a short:

````js
var dll = ffi.LoadLibrary('myDLL', {
    // ...
    DxSetWindowPlacement: ['short', ['int']]
});

dll.DxSetWindowPlacement(1); // works in nodejs, not in electron
````

The C header file contains:

````c
#ifdef WINDOWS
extern "C" short WINAPI DxSetWindowPlacement (
    UINT uShowCmd
    );
#else
// ...
````

In the end, the DLL will call the ShowWindow function: [MS doc](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633548(v=vs.85).aspx)

Should I report the issue to electron?
How can I tackle this issue? Can I provide more information?

Thanks in advance for your help!

**Comment by TooTallNate** [comment]
Possibly related to how they integrate with the Windows event loop, but I'm just guessing and don't know how electron is actually implemented.

I would probably try pinging the electron team and seeing if they have any ideas.

**Comment by unbornchikken** [comment]
I think the difference is that node.js application is a console application, and electron use windowed mode. That leads to different window defaults, and [Remarks on MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633548(v=vs.85).aspx) states:

*As noted in the discussion of the nCmdShow parameter, the nCmdShow value is ignored in the first call to ShowWindow if the program that launched the application specifies startup information in the structure. In this case, ShowWindow uses the information specified in the STARTUPINFO structure to show the window. On subsequent calls, the application must call ShowWindow with nCmdShow set to SW_SHOWDEFAULT to use the startup information provided by the program that launched the application. This behavior is designed for the following situations ...*

Try to call that method twice, it might help.

**Comment by antoinepairet** [comment]
@TooTallNate, @unbornchikken Thanks for your advice and input.
I will ping the electron team and ask them for help.

As far as calling the function twice or more, it does not have an impact. I also tried different values without success.

**Comment by antoinepairet** [comment]
We found a bug in our code. Shame on me. :-s.
To recap: from the renderer process, we successfully call showWindow through a DLL through ffi. It works on Win7 and Win8. Not tested under Win10.
Sorry for the confusion.
regards
