### ISSUE TITLE
node-ffi can't run under Node.js v5.0.0

### ISSUE THREAD

**Issue by naderalbes** [node-ffi/node-ffi#259]
FATAL ERROR: v8::ArrayBuffer::Neuter Only externalized ArrayBuffers can be neutered

**Comment by unbornchikken** [comment]
It's starting to get tiresome ... They are into this: https://github.com/nodejs/node/issues/3619 Let's wait for the result of that.

**Comment by kjunichi** [comment]
Hi, I don't have  any solutions but,
I found that.

when  GC ran,the errors occur

```js
var ffi = require('../')

var funcPtr = ffi.Callback('int', [ 'int' ], Math.abs)
var func = ffi.ForeignFunction(funcPtr, 'int', [ 'int' ])

func(-3)
global.gc()
func(-3)
```

```bash
node --expose_gc test.js
```

**Comment by unbornchikken** [comment]
In @indutny we trust. :) As always.

**Comment by naderalbes** [comment]
@unbornchikken sorry i don't see it before

**Comment by unbornchikken** [comment]
Fix's been landed https://github.com/nodejs/node/commit/827ee498e332e316421f565c5f763f347f81274c. Now we gotta wait for the next release. Keepin' this issue open till it resolved.

**Comment by timkurvers** [comment]
Node 5.1.0 was [just released](https://nodejs.org/en/blog/release/v5.1.0/) which seems to include the fix!

**Comment by unbornchikken** [comment]
Could anyone confirm that this issue got resolved? I'm not able to test it with new node right now.

**Comment by kjunichi** [comment]
It works fine for me!
And above code does not put any errors.

**Comment by timkurvers** [comment]
Can also confirm that it works here :)

**Comment by naderalbes** [comment]
hi can also confirm that it works

**Comment by unbornchikken** [comment]
Kewl.
