### ISSUE TITLE
can't work probably with node v4.0+

### ISSUE THREAD

**Issue by kimtn-bitmark** [node-ffi/node-ffi#262]
I have a project are working well on node v0.12. But when i upgrade nodejs version to 4.0 i got segmentation fault 
```
/home/vagrant/tweetnacl-nodewrap/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x1b43)[0x7fa51b7dcb43]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340)[0x7fa522415340]
node(_ZN2v88internal20StaticMarkingVisitorINS0_32IncrementalMarkingMarkingVisitorEE18VisitJSArrayBufferEPNS0_3MapEPNS0_10HeapObjectE+0x7e)[0xacc82e]
node(_ZN2v88internal18IncrementalMarking4StepElNS1_16CompletionActionENS1_18ForceMarkingActionENS1_21ForceCompletionActionE+0x2bd)[0xad268d]
node(_ZN2v88internal8NewSpace15SlowAllocateRawEiNS0_19AllocationAlignmentE+0x74)[0xb01774]
node(_ZN2v88internal4Heap11AllocateRawEiNS0_15AllocationSpaceES2_NS0_19AllocationAlignmentE+0x1b9)[0xa64339]
node(_ZN2v88internal4Heap16AllocateJSObjectEPNS0_10JSFunctionENS0_13PretenureFlagEPNS0_14AllocationSiteE+0x6b)[0xab419b]
```
But the weird are it does not fail immediately, it's just fail when i try to run many test cases (about 3000 cases). And i got fault when i ran about from 2100 to 2300 cases.

*NOTE*: refer my project here https://www.npmjs.com/package/tweetnacl-nodewrap

Sorry for my english skill.

**Comment by unbornchikken** [comment]
Exactly which version of Node.js are you using? Because ffi only support Node.js from 4.1 beacuse of buffer issues at Node/v8 side: https://github.com/node-ffi/node-ffi/issues/238

**Comment by kimtn-bitmark** [comment]
I'm using node v4.0.0

**Comment by kimtn-bitmark** [comment]
@unbornchikken : just test with node v4.1 it's ok. Thanks. i think we can close this issue.
Thanks so much.
