### ISSUE TITLE
Library functions that have a callback argument?

### ISSUE THREAD

**Issue by cronvel** [node-ffi/node-ffi#263]
Does node-ffi supports callback arguments? I can't find anything in the doc neither here and neither in the "ref" module's doc.

I'm trying to create bindings for libnotify. I was succeeding until I reached [this function](https://developer.gnome.org/libnotify/unstable/NotifyNotification.html#notify-notification-add-action):
```
void notify_notification_add_action (
    NotifyNotification *notification,
    const char *action,
    const char *label,
    NotifyActionCallback callback,
    gpointer user_data,
    GFreeFunc free_func);
```
Note the `NotifyActionCallback callback` argument.

I don't have any clue.

BTW thanks for this awesome module!

**Comment by cronvel** [comment]
Okey, I found my answer in the source code:

var *fnPtr* = ffi.Callback( *return_type* , [ *arg1_type* , ... ] , *javascript_function* ) ;

**Comment by TooTallNate** [comment]
`ffi.Callback` works, but `ffi.Function` is a bit more high-level, you can define the `NotifyActionCallback` type properly and then just pass a JS function to `notify_notification_add_action` once it's defined.

There's not really good documentation on it at the moment, but [take a look at the tests to get an idea](https://github.com/node-ffi/node-ffi/blob/04687f3f8f2230450fc3565923f88dde418f7ad9/test/function.js#L32-L33).

**Comment by cronvel** [comment]
Thanks a lot, it works like a charm! ;)

**Comment by vinipsmaker** [comment]
Hi guys, sorry about "necro-bumping" the issue, but does this callback can be "saved" and called from other threads?

From the looks on the source code, it looks like it's properly protected with mutexes and it'll schedule the JS function to be called from the uv thread. Can I assume this just work then? I need to use it for a time-consuming heavy native function that receives the C callback as argument, spawns a thread and call the callback when result is ready.
