### ISSUE TITLE
Null function pointer?

### ISSUE THREAD

**Issue by tysenmoore-xse** [node-ffi/node-ffi#264]
I have an API with an optional function pointer.  Is there a way to pass this as a NULL?  Sorry if you've answered this question, but I looked around and haven't seen it.

**Comment by TooTallNate** [comment]
You should be able to use JS `null` or `ref.NULL`.

**Comment by tysenmoore-xse** [comment]
Thanks for the information.  When I originally tried JS null I got:
uncaughtException: Error: error setting argument 1 - don't know how to set callback function for: null

The ref.NULL worked fine, thanks.
