### ISSUE TITLE
Dynamic Linking Error

### ISSUE THREAD

**Issue by stellasoft-will** [node-ffi/node-ffi#271]
dynamic linking error while trying to access a dll file. for clarification the file can be access by a compiled exe file, which is in the same directory. Tried putting in a direct path, but also no luck, error message below:

C:/test/modules/bin/libmtp-9.dll //printed path

C:\test\node_modules\ffi\lib\dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
    ^

Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (C:\test\node_modules\ffi\lib\dynamic_library.js:74:11)
    at new Library (C:\test\node_modules\ffi\lib\library.js:45:12)
    at Object.<anonymous> (C:\test\modules\index.js:33:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\test\index.js:4:11)

any help would be greatly appreciated.

thanks.

**Comment by antoinepairet** [comment]
The path to your DLL is not correct, [check MS website](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx)
````
ERROR_MOD_NOT_FOUND
126 (0x7E)
The specified module could not be found.
````

**Comment by stellasoft-will** [comment]
i am aware of the error, thanks tho. the problem i am having is why it is throwing the error when i am certain i am giving the correct folder location.

// libmtp definition
var mtp = new ffi.Library(__dirname + "/bin/libmtp-9.dll", {
![libmtp](https://cloud.githubusercontent.com/assets/7594362/12017562/457e8ebe-ad50-11e5-825f-5f151f05a5d8.PNG)

any help with folder path would be appreciated

**Comment by unbornchikken** [comment]
Actually if the dll has been found, but it references some other dlls that is not in the path, you'll get the above error too. Kinda misleading.

**Comment by stellasoft-will** [comment]
well since this i have been able to use the library only if it is is in root of my electron app. works ok from there will do some investigation from there on paths. but now works closing issue
