### ISSUE TITLE
do I need free string/char* return from lib?

### ISSUE THREAD

**Issue by vontio** [node-ffi/node-ffi#277]
when I call free on a returned string application crash with error: pointer being freed was not allocated
free signature:
'free': [
	'void'
	['string']
]

**Comment by hdf** [comment]
You have to free the memory in whichever context it was created in. If the variable is created on node side, free it there, if in the dll, than free it there. You can create a function in the dll, that frees the variable, and call it from node.

**Comment by TooTallNate** [comment]
Use `void*` as the argument type instead of `string`, because `string` is a special intermediary type that allocates a buffer internally based on the JS String that gets passed in.
