### ISSUE TITLE
reinterpret multiple output buffers

### ISSUE THREAD

**Issue by oprince** [node-ffi/node-ffi#279]
My DLL function returns an array of output buffers. Here is the signature:

`EXPORT char * testImage(char *jsonParams, int jsonParamsLength, char* inputs[], char *** output);`

The following Node.js code works well with reinterpreting the first buffer. 
Buffers count and sizes of output buffers are given by the result JSON.
How can I iterate through all output buffers ?

```
var charPtrPtrPtr = ref.refType(charPtrPtr);
var datapointer = ref.alloc(charPtrPtrPtr);

var result = libraryObj.testImage(jsonParams, jsonParams.length, inputsArray, datapointer);

var dataRef = datapointer.deref();
var data = ref.reinterpret(dataRef.deref(), sizeFromResultJSON);
var localBuffer = new Buffer(data);
```

How can I turn the  datapointer reference into an iterate-able Array of buffers ?
The following code (and many other trials) did not work:
```
            var outputsArray = datapointer.deref();
            for (var i = 0; i < resultObj.outputs.count; i++){
                var dataRef = outputsArray[i];
                dataRef.type = charPtr;
                dataRef.length = resultObj.outputs.sizes[i];
                var data = ref.reinterpret(dataRef.deref(), resultObj.outputs.sizes[i]);
                var localBuffer = new Buffer(data);
                localOutputs.push(localBuffer);
            }
```

**Comment by hdf** [comment]
Maybe it would be easier if the output was just a json string? The way you are doing it now, the length has to be set for every level of that multi dimensional array.
This is relevant I think: https://github.com/node-ffi/node-ffi/issues/105#issuecomment-12186007

**Comment by oprince** [comment]
Thanks, The link you have suggested recommends settings the length of returned buffer(s). I tried that, as is shown at the loop code pasted above. Unfortunately it did not help.

**Comment by hdf** [comment]
But have you set the length of every level of every array?

**Comment by oprince** [comment]
Please find below my code. Handling of first buffer code is  OK, I have put it in comment. The loop to iterate all buffers can be found below it.

`/*            //Get only first buffer
            var dataRef = datapointer.deref();
            var data = ref.reinterpret(dataRef.deref(), resultObj.outputs.sizes[0]);
            var localBuffer = new Buffer(data);
            localOutputs.push(localBuffer);
            libraryObj.releaseObject(data);*/

            //get all buffers
            var outputsArray = datapointer.deref();
            for (var i = 0; i < resultObj.outputs.count; i++){
                var dataRef = outputsArray[i];
                dataRef.type = charPtr;
                dataRef.length = resultObj.outputs.sizes[i];
                var data = ref.reinterpret(dataRef.deref(), resultObj.outputs.sizes[i]);
                var localBuffer = new Buffer(data);
                localOutputs.push(localBuffer);
                libraryObj.releaseObject(data);
            }`

The error thrown by Node is for `ref.reinterpret`:

>  TypeError: Object 160 has no method 'deref'

**Comment by hdf** [comment]
I have been playing around with this for a while, and it seems, you might want to use: [ref-array](https://github.com/TooTallNate/ref-array)
I hope you are not trying to read data, that was allocated inside the dll, as that is not accessible I think, you have to create a buffer node side, and write in to that from the dll, or copy stuff over.
I could not get a proper char*** three dimensional array to work so far. It would really be easier if you serialized to json.
Here is what I have been experimenting with: [gist](https://gist.github.com/hdf/2a813c972bf323f3bfc4)
Hope someone smarter comes along, as this is an interesting problem, but am starting to doubt if I can solve it.

**Comment by TooTallNate** [comment]
Look into using ref-array for this. You'd set a ref array as the return type to the FFI'd function, and then set the `.length` to the proper value (`resultObj.outputs.count` in your case, I'm guessing). After that you can iterate over the array like a regular JS Array.

**Comment by oprince** [comment]
Huge thank for your help !:) It works with `ref-array`
Here are the relevant code lines:

``` js
var charPtrArray = ArrayType('char *');
var charPtrArrayPtr = ref.refType(charPtrArray);
var datapointer = ref.alloc(charPtrArray);
...
var result = libraryObj.testImage(jsonParams, jsonParams.length, inputsArray, datapointer);
...
var outputs = datapointer.deref();
outputs.length = resultObj.outputs.count;

for (var i = 0; i < resultObj.outputs.count; i++){
    dataRef = outputs[i];
    dataRef.type =  ref.coerceType('char *');
    dataRef.length = resultObj.outputs.sizes[i];
    var data = ref.reinterpret(dataRef, resultObj.outputs.sizes[i]);
    var localBuffer = new Buffer(data);
    localOutputs.push(localBuffer);
    libraryObj.releaseObject(data);
}
```
