### ISSUE TITLE
buffer dereference issue in node.js using ffi & ref

### ISSUE THREAD

**Issue by tonyguo1987** [node-ffi/node-ffi#281]
I have an issue in dereferencing a buffer using ffi and ref in Node.js. I created javascript wrapper using ffi to call dll functions. What I am doing below is passing a different types of pointer to pointer to dll, allocate memory in dll, and assign values to these memory. Then read these values back in javascript.

Here is my C++ functions.

```
#ifdef __cplusplus
extern "C" {
#endif
_declspec(dllexport) void testFloatPtr(float *resultPtr){
    resultPtr[0] = 1.5;
}

_declspec(dllexport) void testFloatPtrPtr(float **resultPtrPtr){
    float *resultPtr = *resultPtrPtr = new float[3];
    resultPtr[0] = 1.1;
    resultPtr[1] = 10.1;
    resultPtr[2] = 100.1;
}

_declspec(dllexport) void testIntPtrPtr(int **resultPtrPtr){
    int *resultPtr = *resultPtrPtr = new int[3];
    resultPtr[0] = 2;
    resultPtr[1] = 3;
    resultPtr[2] = 4;
}

_declspec(dllexport) void testCharPtrPtr(char **resultPtrPtr){
    char *resultPtr = *resultPtrPtr = new char[3];
    resultPtr[0] = 5;
    resultPtr[1] = 6;
    resultPtr[2] = 7;
}
#ifdef __cplusplus
}
#endif
```
Here is my javacript application.

```
var ref = require('ref');
var ffi = require('ffi');

var mylib = ffi.Library('debug', {
    'testFloatPtr' : ['void', ['float*']],
    'testFloatPtrPtr':['void', ['float**']],
    'testIntPtrPtr' : ['void', ['int**']],
    'testCharPtrPtr': ['void', ['char**']]
});

var ptr1 = ref.alloc('float');
mylib.testFloatPtr(ptr1);
var result1 = ref.deref(ptr1);
console.log("result1: ", result1);

var ptrptr2 = ref.alloc('float*');
mylib.testFloatPtrPtr(ptrptr2);
var ptr2 = ref.deref(ptrptr2);
var result2 = ref.reinterpret(ptr2, 3, 0);
console.log("result2[0]: ", result2[0]);
console.log("result2[1]: ", result2[1]);
console.log("result2[2]: ", result2[2]);

var ptrptr3 = ref.alloc('int*');
mylib.testIntPtrPtr(ptrptr3);
var ptr3 = ref.deref(ptrptr3);
var result3 = ref.reinterpret(ptr3, 3, 0);
console.log("result3[0]: ", result3[0]);
console.log("result3[1]: ", result3[1]);
console.log("result3[2]: ", result3[2]);

var ptrptr4 = ref.alloc('char*');
mylib.testCharPtrPtr(ptrptr4);
var ptr4 = ref.deref(ptrptr4);
var result4 = ref.reinterpret(ptr4, 3, 0);
console.log("result4[0]: ", result4[0]);
console.log("result4[1]: ", result4[1]);
console.log("result4[2]: ", result4[2]);
```
And here is my console output:

```
result1:  1.5
result2[0]:  205
result2[1]:  204
result2[2]:  140
result3[0]:  2
result3[1]:  0
result3[2]:  0
result4[0]:  5
result4[1]:  6
result4[2]:  7
```
result1 and result4 are OK but result2 and result3 are wrong. It seems that somethings is wrong with dereferencing the buffer with type 'float**' and 'int**'. However, it works for 'char**'.

Could you help me with it? Thank you!

**Comment by TooTallNate** [comment]
Look into using [`ref-array`](https://github.com/TooTallNate/ref-array) for the array types. I suspect that you're actually interpreting the byte location of your array, rather than its contents.

**Comment by tonyguo1987** [comment]
Thank you for your comment. If I change it to ref-array, it works fine. But what I am curious about is that, is my usage of ref wrong? Very appreciated if you can tell me why.

**Comment by TooTallNate** [comment]
When you're calling `var result2 = ref.reinterpret(ptr2, 3, 0)` you're getting back a Buffer with a `length` of 3 _bytes_, as opposed to the 3 _floats_ that you're interested in.

Instead, you'd want to do something like `var result2 = ref.reinterpret(ptr2, 3 * ref.sizeof.float, 0)`, and then call `ref.get(result2, i * ref.sizeof.float, ref.types.float)` 3 times, replacing `i` with 0-2.

Make sense?

**Comment by tonyguo1987** [comment]
Thank you very much!
