### ISSUE TITLE
Problem with SetWindowsHookEx (user32.dll)

### ISSUE THREAD

**Issue by ldp-n** [node-ffi/node-ffi#286]
Hello. I am trying to handle keystrokes on Windows.
```
var ffi = require('ffi'),
    ref = require('ref');

function call(nCode, wParam, lParam){
    console.log(lParam);
    return user32.CallNextHookEx(nCode, wParam, lParam);
}

var intPtr = ref.refType('int');
var funcPtr = ffi.Callback(intPtr, ['int', intPtr, intPtr], call);

var user32 = new ffi.Library('user32', {
    'SetWindowsHookExW': [intPtr, ['int', 'pointer', intPtr, 'int']],
    'CallNextHookEx': [intPtr, ['int', intPtr ,intPtr]],
    'UnhookWindowsHookEx': ['bool', [intPtr]],
});

var hook = user32.SetWindowsHookExW(13, funcPtr, ref.NULL, 0);
```
The hook was successfully set, but the callback hasn't been called and keyboard input was lagging while process was running.
When I send keystokes from my application in same thread
```
user32.keybd_event(0x41, 0, 0, 0);
user32.keybd_event(0x41, 0, 2, 0);
```
`call` runs.
When I send those keystrokes from another thread, `call` doesn't run.
Could you please explain me what should I do to fix this problem?
Thanks.

**Comment by TooTallNate** [comment]
@ldp-n Did you figure it out?

**Comment by ldp-n** [comment]
Yes. I realized that I had to use `GetMessage`

**Comment by aow73320** [comment]
@ntlvs can i see full code?
im  new
thank you
