### ISSUE TITLE
How to add folder to autoload paths?

### ISSUE THREAD

**Issue by d9k** [node-ffi/node-ffi#288]
Hello!
I try to load with `ffi.Library()` some library located at the certain directory (for example `lib/myLib.dll`). But this library is linked to another library (for example `core.dll`). I thought `myLib.dll` would search for core library at the same folder (`lib/core.dll`), but it searches core library at the application's root folder (I know this because I tried to move `core.dll` to the root application folder and loading works).
So how can I add `lib/` path to the autoload paths? I mean, paths which are traversed when one dll tries to load another it depens on?

**Comment by TooTallNate** [comment]
DLL load paths are described for Windows here: https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx#standard_search_order_for_desktop_applications

I believe you're going to want to call the [`SetDllDirectory()`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686203(v=vs.85).aspx) function to add some more paths.

**Comment by d9k** [comment]
thanks, @TooTallNate ! How can I call this function from node.js in most simple way? Can I call it from node-ffi? Sorry, I can't understand in which system library `SetDllDirectory()` is located. Or maybe do there exist some other ways to achieve similar results?

**Comment by TooTallNate** [comment]
Yes, use node-ffi for this.

**Comment by rsfernandes** [comment]
I'm facing the same issue, ffi can't find the FreeImage.dll (which my DLL depends on) if its not in my project root folder. The problem is I want to put all my DLL's in a ./lib folder not in the project root. Some example?

**Comment by d9k** [comment]
@rsfernandes, didn't solve it too, I just place dlls at the project root

**Comment by rsfernandes** [comment]
Thanks to share it. We are doing the same.

**Comment by insightcoder** [comment]
Windows looks for DLLs on your system path, so you can either add the directories to the Path environmental variable, or you can modify the Path as you are going.  Here is what I am doing that seems to be working for now:

```javascript
var oldPath = process.env.PATH;
var dllPath = 'path/to/dlls';
process.env['PATH'] = `${process.env.PATH};${dllPath}`;

var lib = ffi.Library('MyLibrary', {});

process.env['PATH'] = oldPath;
```

**Comment by BONDbATIF** [comment]
@insightcoder 
In some of machine after setting path to system variable then also this is not working .To make work i have to put all the dlls to root directory . 
do you have any idea ?

**Comment by insightcoder** [comment]
@BONDbATIF Are you on Windows/Linux/Mac?  If on mac/linux the above code may not work exactly since it hard-coded path separator ";".  I probably should have used `path.delimiter` to be cross-platform.  Another issue I have run into in the past, particularly on Windows, was some max-path limitations.  If this is the problem you could try _prepending_ the `dllPath` to the system path instead of appending.

**Comment by BONDbATIF** [comment]
Well I am working in Windows.I tested in both scenario.In both case for me its not working. 
Below path i pretended to system path .
C:\SVNWorkSpace\UI\SpotProClient\server\spotpro_bin;
No idea whats going on, for some of my team mates this approach is working fine .I checked in dependency walker .there also i did not got any clue .We are in dilemma ,safe side is to put dll in root directory, that work every time.

**Comment by insightcoder** [comment]
@BONDbATIF Can you post your code that does the path-setting?  I just tested again and could not get it _NOT_ to work.  Is the windows path getting loaded correctly? (ie. double backslashes, or forward slashes)

**Comment by BONDbATIF** [comment]
var ffi = require('ffi'),
	ref = require("ref"),
	serverConnWrapperPath,
	longPtr = ref.refType('long'),
	async = require('async'),
	stringPtr = ref.refType(ref.types.CString);

var fs = require('fs');

console.log("Loading SpotProList Module...");
if (process.platform == "win32") {
	serverConnWrapperPath = __dirname + "\\..\\server\\spotpro_bin\\SCMuiWrapper";
} else {
	// for MAC 
	serverConnWrapperPath = __dirname + "/../server/spotpro_bin/libSCMuiWrapper";
}

console.log("serverConnWrapperPath :" + serverConnWrapperPath);
//Creating Node wrapper library for native methods
var wrapperLibrary = ffi.Library(serverConnWrapperPath, {
	"connectToServer": ["bool", ["string", "string", "string", "string"]],
	"disconnectFromServer": ["void", []],
	"GetSpotColorGroupsJson": ["char *", ["string"]],
	});
spotpro_bin PATH  is pretended in system path .
And below are my folder structure .
SpotProClient\server\spotpro_bin- dlls 
SpotProClient\electron-electron launching js file(index.js) and ffi node script file(here i am trying to load dlls).
please find the image
![dll issue](https://user-images.githubusercontent.com/5045450/37783231-f72df882-2e1a-11e8-87be-fa5f389c4da9.JPG)

**Comment by insightcoder** [comment]
@BONDbATIF 

Try something like this:
`
var libPath = path.join(__dirname, '..', 'spotpro_bin');
var libName = process.platform === "win32" ? 'SCMuiWrapper' : 'libSCMuiWrapper';
process.env.PATH = `${process.env.PATH}${path.delimiter}${libPath}`;

var wrapperLibrary = ffi.Library(libName, {...})
`

**Comment by BONDbATIF** [comment]
@insightcoder :Thanks for your response I tried but still getting same problem .
 ng:///AppModule/AppComponent_Host.ngfactory.js:5 ERROR Error: Dynamic Symbol Retrieval Error: Win32 error 127
    at DynamicLibrary.get (C:\EFI_Workspace\spotProUI\UI\SpotProClient\node_modules\ffi\lib\dynamic_library.js:112:11)
    at C:\EFI_Workspace\spotProUI\UI\SpotProClient\node_modules\ffi\lib\library.js:50:19
    at Array.forEach (<anonymous>)
    at Object.Library (C:\EFI_Workspace\spotProUI\UI\SpotProClient\node_modules\ffi\lib\library.js:47:28)
    at Object.<anonymous> (C:\EFI_Workspace\spotProUI\UI\SpotProClient\electron\spotpromodule.js:28:26)
    at Object.<anonymous> (C:\EFI_Workspace\spotProUI\UI\SpotProClient\electron\spotpromodule.js:909:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

**Comment by waitingsong** [comment]
@BONDbATIF  
You got `Win32 error 127`, means dll can be found, but got error during load dll. check you definition, like this:
```js
var wrapperLibrary = ffi.Library(serverConnWrapperPath, {
"connectToServer": ["bool", ["string", "string", "string", "string"]],  // <-------- maybe wrong params or param type
"disconnectFromServer": ["void", []], // <-------- maybe wrong params or param type
"GetSpotColorGroupsJson": ["char *", ["string"]], // <-------- maybe wrong params or param type
});

```

**Comment by BONDbATIF** [comment]
@waitingsong @TooTallNate @insightcoder @d9k @rsfernandes 
checked all things ,The problem is same code working in some machine .Is something depends on OS ?
Dont know, in production whats is going to happen .
Could anybody tell me ,Which place i should put dll , so it will safe (All time it should work) .

**Comment by BONDbATIF** [comment]
dll and node env both are in 32 bit .this problem is coming in sometime machine .
Same dll is working in another machine .we tried in more the 3-4 machine .out of 5 machine 4 machine ,it is working file .5 machine few days back also working .

**Comment by liuyiliuyi** [comment]
@BONDbATIF  Hi, Has this problem been solved ? 🙏

**Comment by liruisen** [comment]
I referred to this scheme and solved the problem of Win32 Error 126. Thanks !
