### ISSUE TITLE
Streaming with node-ffi ?

### ISSUE THREAD

**Issue by oprince** [node-ffi/node-ffi#291]
If it possible to create a Stream object in Node.js code and pass it to native library for further processing ?
Is the opposite direction possible ?
Thanks!
Orit

**Comment by TooTallNate** [comment]
Probably a dup of #276, but the short answer is no, you have to implement the stream base class (`Readable`, `Writable`, `Transform`) manually using the FFI functions.

For example, [`node-speaker` implements Writable](https://github.com/TooTallNate/node-speaker/blob/9ebdf3d419433f96e0d196843ac9716edd2f01b3/index.js#L219-L280) by calling the native functions (this isn't FFI in this case, but the same concept still applies).

Hope that helps!
