### ISSUE TITLE
Feature request: support for Microsoft Windows

### ISSUE THREAD

**Issue by Mithgol** [node-ffi/node-ffi#30]
Several latest versions of Node.js support Microsoft Windows.

[libffi homepage](http://sourceware.org/libffi/) says the library can also work on Windows. (To be precise: [atgreen/libffi](https://github.com/atgreen/libffi/) says the project can be compiled by Microsoft's Visual C++ compiler since version 3.0.10 of libffi, which is dated Aug-23-11.)

Is it possible to hope that node-ffi would eventually be ported to Microsoft Windows as well? It would make writing numerous wrapper modules (around existing libraries) a whole lot easier, and in some cases that would also facilitate providing pre-compiled binaries to end users.

**Comment by AndreKR** [comment]
This looks great and gave me hope, but... where is it?

**Comment by AndreKR** [comment]
Ah, found it... in 0.5.7, but for Node 0.6. Seems like since then no one took the trouble to build a new release and maybe add a `binary` section to package.json for node-pre-gyp? Or am I missing something?

**Comment by TooTallNate** [comment]
@AndreKR There is no precompiled binary of node-ffi at this time.
