### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by Outlooks** [node-ffi/node-ffi#302]
I'm trying to run an app of node-ffi on my windows 7 PC with Nodejs v6.2.0, but it crashes with the following error . I tried a variety of methods, but did not resolve my problem:

```
E:\iwork\workbase\myapp\node_modules\bindings\bindings.js:91 Uncaught Error: Could not locate the bindings file. Tried:
 → E:\iwork\workbase\myapp\node_modules\ref\build\binding.node
 → E:\iwork\workbase\myapp\node_modules\ref\build\Debug\binding.node
 → E:\iwork\workbase\myapp\node_modules\ref\build\Release\binding.node
 → E:\iwork\workbase\myapp\node_modules\ref\out\Debug\binding.node
 → E:\iwork\workbase\myapp\node_modules\ref\Debug\binding.node
 → E:\iwork\workbase\myapp\node_modules\ref\out\Release\binding.node
 → E:\iwork\workbase\myapp\node_modules\ref\Release\binding.node
 → E:\iwork\workbase\myapp\node_modules\ref\build\default\binding.node
 → E:\iwork\workbase\myapp\node_modules\ref\compiled\6.1.0\win32\ia32\binding.node
```

**Comment by TooTallNate** [comment]
This generally means that the `npm install ffi` step (the compilation step) failed. Is there anything else is your logs?

**Comment by belohlavek** [comment]
Having the same problem with Ubuntu for windows 10 (linux subsystem)

see https://github.com/exponentjs/exp/issues/11

**Comment by TooTallNate** [comment]
Open new issues with specific error messages please.

**Comment by netcore-jroger** [comment]
@chlk1234 if you using electron, please see [using-native-node-modules](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md).
