### ISSUE TITLE
is there a way to decrease the delay between frequently called async functions that consumes too much time?

### ISSUE THREAD

**Issue by seightday** [node-ffi/node-ffi#303]
Hi, I'm using node-ffi with nwjs to invoke functions provided by dlls, I encounter a problem that when I call functions that consumes too much time frequently then the responses will be delayed severely.
I have push my code to https://github.com/seightday/nwjs_node_ffi_async_delay_test

click nwapp/runsdk.bat to start nwjs

nwapp/test.html calls the async functions,
var dll =ffi.Library('dll/demojson1', {
	'DllJson': [ 'string', [ 'string' ] ]
});
dll.DllJson(JSON.stringify({Name:'test',TimeOut:2000}))//the Timeout:2000 parameter tells the dll to sleep 2000ms

nwapp/test.log-2016-05-30 is the result

![test.log](https://cloud.githubusercontent.com/assets/4198029/15647421/0a9bc4dc-2696-11e6-9f18-cd4dca7965f7.png)
![test.html](https://cloud.githubusercontent.com/assets/4198029/15647466/4f1581ca-2696-11e6-9cc0-69efd7e2598d.png)
As the code shows, I expect "test2 1 result is" is logged after one seconds when "test - invoke test2" has been logged, but the delay is 9 seconds.

If there is a way to decrease the delay between frequently called async functions that consumes too much time?

Thanks

**Comment by seightday** [comment]
I wonder that the size of the thread pool is 4, how can I increase the size?

**Comment by berton1679** [comment]
Yes, the size of thread pool is 4.
http://docs.libuv.org/en/v1.x/threadpool.html
The thread pool mechanism of Node.js is based on libuv, and the default value is 4.
You can modify the default value by following command.
**win:**

> SET UV_THREADPOOL_SIZE=128& node test.js

**unix:**

> UV_THREADPOOL_SIZE=128 node test.js

or

**add**

> process.env.UV_THREADPOOL_SIZE=128;

However, the above code is not working on the Windows platform....

Thanks

**Comment by seightday** [comment]
@berton1679 thanks
