### ISSUE TITLE
Question: How to use node-ffi with an library that has a function to return a list of functions

### ISSUE THREAD

**Issue by rmhrisk** [node-ffi/node-ffi#304]
In PKCS#11 there is an API called C_GetFunctionList that returns a list of available functions. Not all libraries export the list of functions and expect you to use this to get the function names.

We have a library that wraps PKCS#11 for Node (https://github.com/PeculiarVentures/graphene/issues/38) and we have encountered one such library.

We would like to support these cases but are not clear on how one does this with node-ffi, your help is appreciated.

**Comment by rmhrisk** [comment]
@TooTallNate sorry to bother you but can you point me in the right direction.

**Comment by TooTallNate** [comment]
@rmhrisk Can you show me some of the C code that you're trying to port to JS? Sorry for the delay by the way!

**Comment by rmhrisk** [comment]
No worries, we ended up rewriting without FFI thanks for the offer to help.
