### ISSUE TITLE
Windows DDLs being built without exported functions

### ISSUE THREAD

**Issue by PlasmaPower** [node-ffi/node-ffi#307]
Replaces #120 with new information from cjlarose/argon2-ffi#20.

DLLs built on Windows (sometimes?) have no exported functions. This can be confirmed with the command `dumpbin /exports built.dll`. Results can be seen [here](https://github.com/cjlarose/argon2-ffi/issues/20#issuecomment-230100842). A normal result would look like [this](http://stackoverflow.com/a/6634722/3352674). This causes the win32 error 127, could not load the specified procedure. That is because the specified procedure (function) is not in the DLL.

[This binding.gyp](https://github.com/cjlarose/argon2-ffi/blob/master/binding.gyp) can replicate it, although there is nothing too special in there.

**Comment by PlasmaPower** [comment]
I think we've found the root problem in that thread:

> It looks like the problem is that for VS you have to put __declspec(dllexport) before any function you want to export when building a DLL. That's why our built DLLs have no functions.
> There's no way to automatically export all functions (that's built into VS at least), so it looks like it won't easily work unless argon2 adds specific support for Visual Studio.

Could `node-ffi` handle this automatically? It would be hard to automatically instert `__declspec` into the code, but VS provides another way. [A module definition file](https://msdn.microsoft.com/en-us/library/28d6s79h(VS.80).aspx) could specify functions that need exported. However, you first have to determine which functions need exported and then put them in a file. Anybody have a good idea on how to do this? I know CMake handles this somehow.

**Comment by PlasmaPower** [comment]
While in this case the issue was easily fixable thanks to already having ARGON2_PUBLIC which can be adjusted to `__declspec(dllexport)`, many projects are not that planned. A more general automated solution would be very nice.

**Comment by TooTallNate** [comment]
I think what you're looking for is the `ModuleDefinitionFile` in gyp. See node-ogg for an example: https://github.com/TooTallNate/node-ogg/blob/b7fa35df9ed859901eb6d0316bf6e147b6bb13b1/binding.gyp#L30-L36

**Comment by PlasmaPower** [comment]
@TooTallNate I see, that's very useful. I've not seen that in a node-ffi project before. Complete automation like CMake would be nice, but I think that's out of the scope of this project. Therefore, I'm closing this issue. If anyone has a good idea on how to automate this (with a library or such) I can reopen this.
