### ISSUE TITLE
Node-Ffi runs perfectly for first time and then gives segmentation fault 11 or garbage value

### ISSUE THREAD

**Issue by aamte** [node-ffi/node-ffi#311]
My index.js file is as follows:

``` js
var ffi = require('ffi')
var libREmake_web = ffi.Library('/Users/Documents/rematch/src/src/libtest_web', {
	'UploadSingleRule': ['string',['string','string']],
	'UploadFile': ['string',['string','string']]
})

var output = libREmake_web.UploadFile("input.json","targetfile.json")
console.log(output)
```

My C++ file is as follows:

``` c++
#if defined(WIN32) || defined(_WIN32)
#define EXPORT __declspec(dllexport)
#else
#define EXPORT
#endif

extern "C" {

/// Prototypes
static std::string
ConvertToJson(const size_t &num,
const std::vector &result,
const std::string &error);

EXPORT const char *remake::UploadSingleRule(const std::string &rule,
const std::string &targetFile) {
//code
const char *jsonReply = json.c_str();
return jsonReply;
}

EXPORT const char *remake::UploadFile(const std::string &filename,
const std::string &targetFile) {
//code
const char *jsonReply = json.c_str();
return jsonReply;
}
```

C++ header file:

``` c++
#ifndef REMAKE_WEB_H
#define REMAKE_WEB_H

extern "C" {
namespace remake {

const char *UploadSingleRule(const std::string &rule,
const std::string &targetFile);
const char *UploadFile(const std::string &filename,
const std::string &targetFile);
}
}

#endif
```

Output:

```
$ node index.js
{
"Number": "1",
"Error": "",
"Regex": ""
}

$ node index.js
Segmentation fault: 11
$ node index.js
@<�
```

Kindly let me know where I am going wrong as it gives me correct output for the first time I run it and then it keeps giving segmentation fault:11 or some garbage value.

**Comment by TooTallNate** [comment]
Well in general ffi isn't designed to work with C++ binaries... And a `std::string` is not the same thing as a C `char *` string, so that's probably along the lines of where you're getting hung up. Try changing the parameter types to `char *` instead of `std::string`.

**Comment by aamte** [comment]
Changed the parameters to char *, still facing the same issue.

**Comment by aamte** [comment]
So if I add a dummy function which takes string as an input and returns the same back like so:

EXPORT const char *remake::trialupload(const char *name) { return name; }

and call it before I call my actual function, it seems to work smoothly. If I don't and just call my desired function, it gives segmentation fault: 11.

index.js:
var output = libREmake_web.trialupload("Hello")
var json = libREmake_web.UploadSingleRule("abcd/srdf","targetfile.json")
console.log(son)

So any pointers on what might be happening and how to address this issue?

**Comment by TooTallNate** [comment]
Honestly I'd try making a C lib instead of a C++ one.

**Comment by aamte** [comment]
Okay. Thank you for taking out time and looking at it.

**Comment by MeirionHughes** [comment]
@aamte did making a C library work, or did you give up?
