### ISSUE TITLE
[Help Wanted] How to get the result of a pointer

### ISSUE THREAD

**Issue by didix16** [node-ffi/node-ffi#317]
Hi guys. I have the following:

``` js
var ptrByteArray = ref.refType('char');
var ptrOutputByteArray = ref.refType('char');
var ptrOutputByteArraySize = ref.refType('int');
var EncryptLib = ffi.Library(path.join(__dirname,'../lib/encrypt.so'),{
    'encrypt': ['int', [ptrByteArray,'int',ptrByteArray,'int',ptrOutputByteArray,ptrOutputByteArraySize] ]
});
```

Which reference to this function in C:

``` c
int encrypt(const unsigned char * input, size_t input_size,
        const unsigned char* iv, size_t iv_size,
        unsigned char* output, size_t * output_size)
```

And afer do the following:

``` js
var outputLength = 32 + bytes.length + (256 - (bytes.length%256));
var ptrOutput = new Buffer(outputLength);
var outputSize = outputLength;
EncryptLib.encrypt(bytes,bytes.length,new Buffer(32),32,ptrOutput,outputSize);
```

I get this error:

```
TypeError: error setting argument 5 - writePointer: Buffer instance expected as third argument.
```

So my question is: how I supose to deal with it, I mean how I should handle the inputs and outputs of the native function with nodejs?

Thanks in advance :)

**Comment by unbornchikken** [comment]
Well, the fifth argument's type is ptrOutputByteArraySize according your declaration. However, you try to invoke that by passing a number there.

**Comment by chengdonglin** [comment]
how to resolve this problem? Thanks!

**Comment by didix16** [comment]
@chengdonglin The solution is what @unbornchikken said. I specified outputSize has pointer argument while outputSize is really a number. That field must be a Buffer object.

`var outputSize = new Buffer();`

**Comment by chengdonglin** [comment]
Thank you for your reply! I  try to wrapper c++ function: 
I have the following:
const ref = require("ref")
const ffi = require("ffi")
const libm = ffi.Library('./TMAPConvert.dll',{
GetNaviImgData:[ref.types.int,['string',ref.refType(ref.types.uchar),'int']]
})
let pcData = new Buffer()
const result = libm.GetNaviImgData('./1.TMAP',pcData,85) 
//when run this methods,I Want to get the real pcData  
console.log(pcData)//pcData is buffer data
Which reference to this function in C++:
HTTPTMAP_API int GetNaviImgData(const char* pcFileName,
unsigned char* pucData,const int nJpegQuality = 85)
when I run js code, I get the error:
	buffer.js:183
       throw new TypeError(kFromErrorMsg);
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

How to deal with this question? Thanks!
发送自 Windows 10 版邮件应用

发件人: didix16
发送时间: 2019年2月14日 3:25
收件人: node-ffi/node-ffi
抄送: chengdonglin; Mention
主题: Re: [node-ffi/node-ffi] [Help Wanted] How to get the result of apointer (#317)

@chengdonglin The solution is what @unbornchikken said. I specified outputSize has pointer argument while outputSize is really a number. That field must be a Buffer object.
var outputSize = new Buffer();

**Comment by chengdonglin** [comment]
Thanks! I have solve this by const outputSize = new Buffer(bufferLength);

**Comment by didix16** [comment]
:+1:  Great :). I'm going to close the issue then.
