### ISSUE TITLE
Is it safe to use `Callback` from another thread? Is it intended? Will stay so in future releases?

### ISSUE THREAD

**Issue by vinipsmaker** [node-ffi/node-ffi#318]
I checked the source code and it seems safe to me (protect access through mutexes, schedule JS execution using libuv...). However, I cannot find if, for instance, this was done to solve some bug in a specific case or is it intended to be thread-safe. Given there is no documentation, I tried to find in closed issues and this is still unclear to me.

Could you clarify, please?

**Comment by vinipsmaker** [comment]
One more question while I'm at it: how do I prevent NodeJS from exitting while I haven't called the callback?

**Comment by unbornchikken** [comment]
It's thread safe. I can use node-ffi for interfacing OpenCL event callbacks in my [NOOOCL](https://github.com/unbornchikken/NOOOCL) module, and it works flawlessly. In NOOOCL I use setTimeouts on async calls to prevent Node.js to shut down: https://github.com/unbornchikken/NOOOCL/blob/master/lib/clUtils.js#L83
