### ISSUE TITLE
Compilation error on Mac OS 10.6.8, node-ffi 2.1.0

### ISSUE THREAD

**Issue by meltedspark** [node-ffi/node-ffi#319]
`node-gyp rebuild` fails with the following error:

> cc1plus: error: argument to '-O' should be a non-negative integer, 'g', 's' or 'fast'
> make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1

`gcc --version`
> gcc-4.8 (Homebrew gcc48 4.8.5) 4.8.5
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`g++ --version`
> g++-4.8 (Homebrew gcc48 4.8.5) 4.8.5
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`node -v`
> v6.4.0

`npm -v`
> 3.10.3

Other native addons pass compilation. 
<details>
<summary>Full stack trace:</summary>
Unhandled rejection Error: /usr/local/bin/node exited with code 1
Output:

> ref@1.3.2 install /Users/admin/git/electron-angular2-native/app/node_modules/ref
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/binding.node

> ffi@2.1.0 install /Users/admin/git/electron-angular2-native/app/node_modules/ffi
> node-gyp rebuild

  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o

Error output:
./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw { dev: 234881026,
  mode: 33188,
  nlink: 1,
  uid: 666,
  gid: 80,
  rdev: 0,
  blksize: 4096,
  ino: 1870160,
  size: 1614,
  blocks: 8,
  atime: 2016-08-18T16:43:48.000Z,
  mtime: 2016-08-18T16:43:48.000Z,
  ctime: 2016-08-18T16:43:48.000Z,
  birthtime: 2016-08-18T16:43:48.000Z }
./Release/.deps/Release/obj.target/ffi/deps/libffi/src/prep_cif.o.d.raw { dev: 234881026,
  mode: 33188,
  nlink: 1,
  uid: 666,
  gid: 80,
  rdev: 0,
  blksize: 4096,
  ino: 1870195,
  size: 249,
  blocks: 8,
  atime: 2016-08-18T16:43:51.000Z,
  mtime: 2016-08-18T16:43:51.000Z,
  ctime: 2016-08-18T16:43:51.000Z,
  birthtime: 2016-08-18T16:43:51.000Z }
./Release/.deps/Release/obj.target/ffi/deps/libffi/src/types.o.d.raw { dev: 234881026,
  mode: 33188,
  nlink: 1,
  uid: 666,
  gid: 80,
  rdev: 0,
  blksize: 4096,
  ino: 1870199,
  size: 243,
  blocks: 8,
  atime: 2016-08-18T16:43:51.000Z,
  mtime: 2016-08-18T16:43:51.000Z,
  ctime: 2016-08-18T16:43:51.000Z,
  birthtime: 2016-08-18T16:43:51.000Z }
./Release/.deps/Release/obj.target/ffi/deps/libffi/src/raw_api.o.d.raw { dev: 234881026,
  mode: 33188,
  nlink: 1,
  uid: 666,
  gid: 80,
  rdev: 0,
  blksize: 4096,
  ino: 1870203,
  size: 247,
  blocks: 8,
  atime: 2016-08-18T16:43:51.000Z,
  mtime: 2016-08-18T16:43:51.000Z,
  ctime: 2016-08-18T16:43:51.000Z,
  birthtime: 2016-08-18T16:43:51.000Z }
./Release/.deps/Release/obj.target/ffi/deps/libffi/src/java_raw_api.o.d.raw { dev: 234881026,
  mode: 33188,
  nlink: 1,
  uid: 666,
  gid: 80,
  rdev: 0,
  blksize: 4096,
  ino: 1870207,
  size: 257,
  blocks: 8,
  atime: 2016-08-18T16:43:52.000Z,
  mtime: 2016-08-18T16:43:52.000Z,
  ctime: 2016-08-18T16:43:52.000Z,
  birthtime: 2016-08-18T16:43:51.000Z }
./Release/.deps/Release/obj.target/ffi/deps/libffi/src/closures.o.d.raw { dev: 234881026,
  mode: 33188,
  nlink: 1,
  uid: 666,
  gid: 80,
  rdev: 0,
  blksize: 4096,
  ino: 1870211,
  size: 279,
  blocks: 8,
  atime: 2016-08-18T16:43:53.000Z,
  mtime: 2016-08-18T16:43:53.000Z,
  ctime: 2016-08-18T16:43:53.000Z,
  birthtime: 2016-08-18T16:43:52.000Z }
./Release/.deps/Release/obj.target/ffi/deps/libffi/src/x86/ffi.o.d.raw { dev: 234881026,
  mode: 33188,
  nlink: 1,
  uid: 666,
  gid: 80,
  rdev: 0,
  blksize: 4096,
  ino: 1870217,
  size: 82,
  blocks: 8,
  atime: 2016-08-18T16:43:53.000Z,
  mtime: 2016-08-18T16:43:53.000Z,
  ctime: 2016-08-18T16:43:53.000Z,
  birthtime: 2016-08-18T16:43:53.000Z }
../deps/libffi/src/x86/ffi64.c: In function 'classify_argument':
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an 'else' statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
./Release/.deps/Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o.d.raw { dev: 234881026,
  mode: 33188,
  nlink: 1,
  uid: 666,
  gid: 80,
  rdev: 0,
  blksize: 4096,
  ino: 1870221,
  size: 251,
  blocks: 8,
  atime: 2016-08-18T16:43:53.000Z,
  mtime: 2016-08-18T16:43:53.000Z,
  ctime: 2016-08-18T16:43:53.000Z,
  birthtime: 2016-08-18T16:43:53.000Z }
./Release/.deps/Release/obj.target/ffi/deps/libffi/src/x86/darwin.o.d.raw { dev: 234881026,
  mode: 33188,
  nlink: 1,
  uid: 666,
  gid: 80,
  rdev: 0,
  blksize: 4096,
  ino: 1870225,
  size: 88,
  blocks: 8,
  atime: 2016-08-18T16:43:54.000Z,
  mtime: 2016-08-18T16:43:54.000Z,
  ctime: 2016-08-18T16:43:54.000Z,
  birthtime: 2016-08-18T16:43:53.000Z }
./Release/.deps/Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o.d.raw { dev: 234881026,
  mode: 33188,
  nlink: 1,
  uid: 666,
  gid: 80,
  rdev: 0,
  blksize: 4096,
  ino: 1870229,
  size: 221,
  blocks: 8,
  atime: 2016-08-18T16:43:54.000Z,
  mtime: 2016-08-18T16:43:54.000Z,
  ctime: 2016-08-18T16:43:54.000Z,
  birthtime: 2016-08-18T16:43:54.000Z }
cc1plus: error: argument to '-O' should be a non-negative integer, 'g', 's' or 'fast'
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 10.8.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/admin/git/electron-angular2-native/app/node_modules/ffi
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Darwin 10.8.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "install" "--production" "--cache-min" "999999999"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! ffi@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@2.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ffi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ffi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/git/electron-angular2-native/app/npm-debug.log

  atime: 2016-08-18T16:43:48.000Z,
  atime: 2016-08-18T16:43:51.000Z,
  atime: 2016-08-18T16:43:51.000Z,
  atime: 2016-08-18T16:43:51.000Z,
  atime: 2016-08-18T16:43:52.000Z,
  atime: 2016-08-18T16:43:53.000Z,
  atime: 2016-08-18T16:43:53.000Z,
  atime: 2016-08-18T16:43:53.000Z,
  atime: 2016-08-18T16:43:54.000Z,
  atime: 2016-08-18T16:43:54.000Z,
    at ChildProcess.childProcess.once.code (/Users/admin/git/electron-angular2-native/node_modules/electron-builder/src/util/util.ts:151:14)
    at ChildProcess.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at spawn (/Users/admin/git/electron-angular2-native/node_modules/electron-builder/src/util/util.ts:114:9)
    at spawnNpmProduction (/Users/admin/git/electron-angular2-native/node_modules/electron-builder/src/util/util.ts:43:9)
    at Object.installDependencies (/Users/admin/git/electron-angular2-native/node_modules/electron-builder/src/util/util.ts:21:120)
    at /Users/admin/git/electron-angular2-native/node_modules/electron-builder/src/install-app-deps.ts:30:2
    at next (native)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at tsAwaiter (/Users/admin/git/electron-angular2-native/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at main (/Users/admin/git/electron-angular2-native/node_modules/electron-builder/src/install-app-deps.ts:23:3)
    at Object.<anonymous> (/Users/admin/git/electron-angular2-native/node_modules/electron-builder/src/install-app-deps.ts:35:7)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
</details> 

Any ideas why is this happening and how to fix this?

**Comment by unbornchikken** [comment]
node-ffi only supports clang based compiler on OSX because of its ObjC support (https://github.com/node-ffi/node-ffi/blob/master/binding.gyp#L27).
