### ISSUE TITLE
node-gyp rebuild error Mac OSX 10.11.4

### ISSUE THREAD

**Issue by yilunyu** [node-ffi/node-ffi#320]
I ran node-gyp rebuild command as advised in the README. It gave me the following error: 
`module.js:338
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:434:26)
    at node.js:566:27
    at doNTCallback0 (node.js:407:9)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/Users/yilun/projects/emsdk_portable/node/4.1.1_64bit/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/yilun/projects/ffi-test/node-ffi
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok `

Can someone decipher and help me fix this error please?

**Comment by unbornchikken** [comment]
Yeah, the readme is a bit misleading. Do an

`npm install`

in order to make building work. That'll do a `node-gyp rebuild` implicitly, though.
