### ISSUE TITLE
Dynamically assessing size of array

### ISSUE THREAD

**Issue by smurthy** [node-ffi/node-ffi#325]
If we have a struct via ref-struct as follows:

var StructType = require('ref-struct');
var foo = StructType({
                                  'datamember1' : 'double',
                                  'datamember2' : ArrayType('double', 2)
                                });

This forces me to know the size of datamember2 beforehand but on the C side of things I actually have c++ code which does an extern "C". In there I have a vector of varying size which I convert to a regular array to pass back by reference to the javascript side. 

Is there a way to define datamember2 such that ffi can know the size without me explicitly defining it when the array gets assigned as I call the foreign function?

**Comment by kroggen** [comment]
You can call a function to retrieve the number of doubles and then use it to build the struct object:

```javascript
var count = lib.get_count();

var foo = StructType({
'datamember1' : 'double',
'datamember2' : ArrayType('double', count)
});
```

**Comment by smurthy** [comment]
That works. Thanks.

If this array was created via malloc - how does freeing said memory work from ffi or would I have to take care of it from my library?

**Comment by kroggen** [comment]
When the variable foo is out of scope it will be garbage collected.
