### ISSUE TITLE
Ability to use buffer as Library file.

### ISSUE THREAD

**Issue by ztooner** [node-ffi/node-ffi#326]
I'm writing an Electron app and therefor the Library files will "live" inside an app.asar file. I can reference the file, get stats and so forth but the file does not exist on the file system.
I can open it and create a buffer from it. I'd like to request that you make it possible to use a buffer as well as a filename when creating the Library.

**Comment by TooTallNate** [comment]
I'm afraid I [don't think this is possible](http://stackoverflow.com/a/5053703/376773) (or at least [not portable](https://github.com/m1m1x/memdlopen)). Your best bet might be to write out the file from memory to a temporary space on the file system and then use the Library class on that temporary file path.

**Comment by ztooner** [comment]
It's possible to "unpack" specific files and that is what I do currently, was hoping for a better solution though. Worth a try. :)

**Comment by boshido** [comment]
@ztamizzen 
Can you give me the sample codes of your solution ?
I'm facing this problem.

**Comment by ztamizzen** [comment]
Just add it to your package.json, it's documented and I'm on my phone. Will write later. :-)
