### ISSUE TITLE
Run several async functions in the same thread?

### ISSUE THREAD

**Issue by limenutt** [node-ffi/node-ffi#332]
First of all, node-ffi is great! Many thanks to all collaborators.

I'm currently working on the node wrapper for a C library.
There are several functions in the library that create and manipulate objects. If object is created in one thread, however, it can not be modified in another. High-level operations from the wrapper client perspective require creation and manipulation of the objects. Current implementation of async calls from node to C creates a new thread environment for each call (or so it seems to me after a brief reading of the node-ffi C code).
I wonder if an enhancement could be made allowing to create a tread context in which several ffi calls could be executed? 

From the JS standpoint it would look like 
```
const threadContext = new FFIThreadContext();
const car = library.createCar.asyncInContext(threadContext, brand, model, (error1, car) => {
  if (error1) {
    threadContext.close();
    handleError(error1);
    return;
  }
  library.paintCar.asyncItContext(threadContext, colour, (error2, paintedCar) => {
      if (error2) {
        threadContext.close();
        handleError(error2);
        return;
      }
      doSomething(paintedCar);
      threadContext.close();
    }); 
  }
});
```
Of course in the real world app we would promisify those async functions as well, but that point was to propose how the API could look like.

If the enhancement could not be implemented at the moment or you see no value in it, then any guidance on how to implement it in a fork on my own would be much appreciated.

**Comment by TooTallNate** [comment]
I think you'd want a proper [threads](https://www.npmjs.com/package/threads) or WebWorkers module for this.
