### ISSUE TITLE
async calls with child processes

### ISSUE THREAD

**Issue by haoyangnz** [node-ffi/node-ffi#336]
I'm trying to use node-ffi to asynchronously call a function in a non-threadsafe shared library.

Is there any way for the node-ffi `async` method to spawn a new process (or manage a process pool) instead of a thread pool so I can use the non-threadsafe library concurrently? Maybe via an existing libuv environment variable or an enhancement?

**Comment by haoyangnz** [comment]
I understand I can use child_process to manually manage a process pool, but is there a nicer way?

**Comment by TooTallNate** [comment]
Not really, not built into node-ffi at least. I'd recommend using `child_process.spawn()` to create a worker pool, or there's probably better generic ones on npm as well. Seems out of scope for this module though, so closing.
