### ISSUE TITLE
Doesn't build on OSX anymore

### ISSUE THREAD

**Issue by k1tzu** [node-ffi/node-ffi#337]
$ node-gyp rebuild --verbose
...
c++ '-DNODE_GYP_MODULE_NAME=ffi_bindings' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/ak/.node-gyp/7.0.0/include/node -I/Users/ak/.node-gyp/7.0.0/src -I/Users/ak/.node-gyp/7.0.0/deps/uv/include -I/Users/ak/.node-gyp/7.0.0/deps/v8/include -I../../node_modules/nan -I../deps/libffi/include -I../deps/libffi/config/mac/x64  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -stdlib=libc++ -fno-rtti -fno-threadsafe-statics -fno-strict-aliasing -ObjC++ -MMD -MF ./Release/.deps/Release/obj.target/ffi_bindings/src/ffi.o.d.raw   -c -o Release/obj.target/ffi_bindings/src/ffi.o ../src/ffi.cc
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/node-gyp" "rebuild" "--verbose"
gyp ERR! cwd /Users/ak/Documents/my_company/pet/Port/armuilight/node-ffi
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp

npm@3.10.8
node@v7.0.0
osx@10.12.1

You need to change binding.gyp
from 'MACOSX_DEPLOYMENT_TARGET': '10.5',
to 'MACOSX_DEPLOYMENT_TARGET': '10.7',

**Comment by TooTallNate** [comment]
Fixed in v2.2.0
