### ISSUE TITLE
Segmentation fault by just doing ffi.Library('mylib', {});

### ISSUE THREAD

**Issue by clvLabs** [node-ffi/node-ffi#342]
Hi there,
After upgrading the Node version from 0.12 to 6.9.1 in a project using ffi I'm starting to get segmentation faults.
I've started cutting and cutting code so I could reach the point of failure and this is what I got:

```
var ffi = require('ffi');
console.log('BEFORE ffi.Library()');
var sdk = ffi.Library(__dirname + '/testedlib', {});
console.log('AFTER ffi.Library()');
```

The library under test (_testedlib_) is an .so file in the same folder as the .js file.

... and here's the different outputs:

**Output from Node 0.12.1**

```
$ node index.js
BEFORE ffi.Library()
AFTER ffi.Library()
```

**Output from Node 6.2.0**

```
$ node index.js
BEFORE ffi.Library()
[2]    129858 segmentation fault (core dumped)  node index.js
```

**Output from Node 6.9.1**

```
$ node index.js
BEFORE ffi.Library()
[2]    130507 segmentation fault (core dumped)  node index.js
```

Any thoughts?  

Thanks a lot in advance

**Comment by TooTallNate** [comment]
Well what is `testedlib`? Are you using the latest version of nan with it?

**Comment by clvLabs** [comment]
testedlib.so is a 3rd party proprietary library, we have no access to its code.

When installing ffi, nan v2.4.0 gets installed.

The provider of the library is now having a look at the issue, in the meanwhile they have provided
a temporal workaround. By compiling the following code as a shared library and using it via LD_PRELOAD
seems to fix the issue (at least at first stage).

```c
#define _GNU_SOURCE
#include <dlfcn.h>
#include <stdlib.h>
#include <stdio.h>

static void constructor() __attribute__((constructor));

void constructor()
{
  printf("Loading testedlib.\n");
  void *handle = dlopen("testedlib.so", RTLD_NODELETE|RTLD_DEEPBIND|RTLD_NOW);
  if(handle == NULL) {
    printf("Error opening testedlib\n");
    exit(-1);
  }
  dlsym(handle, "OPENSSL_ia32_cpuid");
  printf("testedlib loaded.\n");
}
```
The code is compiled with
`gcc -nostartfiles -g -shared  -DPIC  -fPIC preload.c -o preload.so`

Then, to test it (assuming all files are in the current folder):
`LD_LIBRARY_PATH=. LD_PRELOAD=./preload.so node index.js`

So, for now I won't bother you anymore with this. If something comes out from this that can be helpful for **ffi** I'll try to get back to you.

Thanks a lot!
