### ISSUE TITLE
Is there a downloadable version that supports node 5?

### ISSUE THREAD

**Issue by oborba** [node-ffi/node-ffi#357]
I tried installing the version ffi@v0.4.2 that appears as the last one with support for node 4, but this version is not available for download in npm, is there any version available that has support for node5?

**Comment by TooTallNate** [comment]
Travis-CI is still testing node v4, v5, and v6. Also ffi@0.4.2 is _ancient_. Which version of Node.js specifically are you using?

**Comment by oborba** [comment]
I'm using node v5.12.0

Thanks for the reply

**Comment by TooTallNate** [comment]
So latest version of ffi should work just fine still. Does `npm install ffi` give you errors?

**Comment by oborba** [comment]
Sorry @TooTallNate, my problem aren't with ffi itself, the problem are my version of npm, when I downloaded the node v5.12.0 it comes with npm with a old version, when update it the installation worked.

After that I needed rebuild ffi and ref with nw-gyp to use ffi in my node-webkit app.

Thanks.
