### ISSUE TITLE
Access constants

### ISSUE THREAD

**Issue by lmatteis** [node-ffi/node-ffi#369]
Is there a way to access constants? For instance I need to access SQLITE_OK https://www.sqlite.org/c3ref/c_abort.html

**Comment by TooTallNate** [comment]
You just need to hard-code them basically. They are not exported symbols in the C library; they only exist in the headers to the preprocessor. So something like:

```js
const SQLITE_OK =          0   /* Successful result */
/* beginning-of-error-codes */
const SQLITE_ERROR =       1   /* SQL error or missing database */
const SQLITE_INTERNAL =    2   /* Internal logic error in SQLite */
…
```
