### ISSUE TITLE
use ffi 2.2.0 error:exists is not a function

### ISSUE THREAD

**Issue by liihuu** [node-ffi/node-ffi#377]
![image](https://cloud.githubusercontent.com/assets/10508024/24575048/dafb1924-16ce-11e7-9f8c-879c30cdb5b4.png)

**Comment by rakeshgn31** [comment]
I have the same problem too. When I run the fs related functions in other projects, I am not getting this error but only with node-ffi. I tried to use fs.accessSync function as replacement and nothing worked. :(
