### ISSUE TITLE
Problems Zero-ing Structure

### ISSUE THREAD

**Issue by harrywhitehouse** [node-ffi/node-ffi#379]
I have a structure which accesses a C-library by reference.  Everything is working with the exception of some garbage bytes in the buffers that are used to return data.

Simple example:

```js
var foo = Struct ({
  'data1'  :  ArrayType('char',50),
  'data2'  :  ArrayType('char',20)
})
```

My understanding is that all the elements in a structure are zeroed when instantiated.  But I find that is not the case for ArrayType's.  For instance if I do this:

    var x = new foo();
    console.log(x.data1);

I get a buffer with a variety of byte values -- many are zero but many are not.

If I make the call to my C function:

    MyFunction(x.ref());

The function returns correct data in data1 and data2, but since the entire buffer is not written, the "garbage" bytes remain as trailing characters.

Is this expected behavior when the Struct contains character arrays?
Is there a way to explicitly 'memset' the instantiated structure as we do in C?
Bonus question out of curiosity:  Is there a call to return to the "sizeof" a structure.  (#.length returns 2 always)

P.S. I did not see this behavior when using Ruby/Rails/FFI against the same DLL.

**Comment by TooTallNate** [comment]
> Is this expected behavior when the Struct contains character arrays?

Whether or not the struct will be initialized to 0s depends on what version of Node.js you're using (newer versions 0-fill new Buffer instances by default). Sorry I can't recall the exact version where that change happened, but:

>  Is there a way to explicitly 'memset' the instantiated structure as we do in C?

`.ref()` gets you the underlying Buffer instance, so you can 0-fill it explicitly with:

```js
x.ref().fill(0)
```

> Bonus question out of curiosity: Is there a call to return to the "sizeof" a structure. (#.length returns 2 always)

Check out `foo.size`.

Hope that helps! Feel free to reply or create a new issue if you have more questions.

**Comment by harrywhitehouse** [comment]
Nathan!

Many, many thanks!!  Thing are working perfectly now!

Best

Harry
