### ISSUE TITLE
STDCALL support?

### ISSUE THREAD

**Issue by MeirionHughes** [node-ffi/node-ffi#383]
I would be grateful if someone could tell me if and how dlls with stdcall methods can be called correctly with this library. Its not very clear anywhere how or if this is possible. There is as blog post here: https://www.kilgus.net/2016/11/29/wrapping-stdcall-functions-in-node-ffi/ that uses `ffi.FFI_STDCALL` but that doesn't seem to be exported on the main library on the latest version.

**Comment by MeirionHughes** [comment]
Its there on 32-bit libs, but not 64-bit (there is no stdcall on 64-bit).

**Comment by andersonjmartins** [comment]
thank´s very much ! u saved my life!
