### ISSUE TITLE
How to pass enum argument to a function using node.ffi module .

### ISSUE THREAD

**Issue by goel-sunny** [node-ffi/node-ffi#387]
I have a structure which i have to pass as a argument to a function , in that structure enumeration is define , now i know how to pass that structure  but in that structure one field is of enumeration type so i am little confuse that how to  create that enum field using node module 
 
enum B
 {
   var 1 , var 2 ,var 3 var 4 
 };

struct A
  {
    int varr1 ;
    char varr2 ;
     char *varr3 ;
    enum B a ;
  }

now how i can create that enum field in the structure in node?

**Comment by matttrawicki** [comment]
Enums are just integers. 0, 1, 2, etc.

**Comment by TooTallNate** [comment]
The [`enum`](https://github.com/adrai/enum) module works nice as well.
