### ISSUE TITLE
Install fail: could not create compact unwind

### ISSUE THREAD

**Issue by EthanBogart** [node-ffi/node-ffi#400]
Hey, I've been having a lot of issues trying to get ffi working. I had to remove python3 from my PATH to get to this point. Now I'm getting this when I try to run `npm install` or `node-gyp rebuild`:

```
> ffi@2.2.0 install /Users/ethan/Projects/node-ffi
> node-gyp rebuild

  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
../src/ffi.cc:111:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("RTLD_NEXT").ToLocalChecked(), WrapPointer((char *)RTLD...
          ^
/Users/ethan/.node-gyp/8.2.0/include/node/v8.h:2950:22: note: 'ForceSet' has been explicitly marked
      deprecated here
                bool ForceSet(Local<Value> key, Local<Value> value,
                     ^
../src/ffi.cc:114:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("RTLD_DEFAULT").ToLocalChecked(), WrapPointer((char *)R...
          ^
/Users/ethan/.node-gyp/8.2.0/include/node/v8.h:2950:22: note: 'ForceSet' has been explicitly marked
      deprecated here
                bool ForceSet(Local<Value> key, Local<Value> value,
                     ^
../src/ffi.cc:117:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("RTLD_SELF").ToLocalChecked(), WrapPointer((char *)RTLD...
          ^
/Users/ethan/.node-gyp/8.2.0/include/node/v8.h:2950:22: note: 'ForceSet' has been explicitly marked
      deprecated here
                bool ForceSet(Local<Value> key, Local<Value> value,
                     ^
../src/ffi.cc:120:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("RTLD_MAIN_ONLY").ToLocalChecked(), WrapPointer((char *...
          ^
/Users/ethan/.node-gyp/8.2.0/include/node/v8.h:2950:22: note: 'ForceSet' has been explicitly marked
      deprecated here
                bool ForceSet(Local<Value> key, Local<Value> value,
                     ^
../src/ffi.cc:123:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("FFI_ARG_SIZE").ToLocalChecked(), Nan::New<Uint32>((uin...
          ^
/Users/ethan/.node-gyp/8.2.0/include/node/v8.h:2950:22: note: 'ForceSet' has been explicitly marked
      deprecated here
                bool ForceSet(Local<Value> key, Local<Value> value,
                     ^
../src/ffi.cc:124:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("FFI_SARG_SIZE").ToLocalChecked(), Nan::New<Uint32>((ui...
          ^
/Users/ethan/.node-gyp/8.2.0/include/node/v8.h:2950:22: note: 'ForceSet' has been explicitly marked
      deprecated here
                bool ForceSet(Local<Value> key, Local<Value> value,
                     ^
../src/ffi.cc:125:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("FFI_TYPE_SIZE").ToLocalChecked(), Nan::New<Uint32>((ui...
          ^
/Users/ethan/.node-gyp/8.2.0/include/node/v8.h:2950:22: note: 'ForceSet' has been explicitly marked
      deprecated here
                bool ForceSet(Local<Value> key, Local<Value> value,
                     ^
../src/ffi.cc:126:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("FFI_CIF_SIZE").ToLocalChecked(), Nan::New<Uint32>((uin...
          ^
/Users/ethan/.node-gyp/8.2.0/include/node/v8.h:2950:22: note: 'ForceSet' has been explicitly marked
      deprecated here
                bool ForceSet(Local<Value> key, Local<Value> value,
                     ^
../src/ffi.cc:132:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("HAS_OBJC").ToLocalChecked(), Nan::New<Boolean>(hasObjc...
          ^
/Users/ethan/.node-gyp/8.2.0/include/node/v8.h:2950:22: note: 'ForceSet' has been explicitly marked
      deprecated here
                bool ForceSet(Local<Value> key, Local<Value> value,
                     ^
9 warnings generated.
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
  SOLINK_MODULE(target) Release/ffi_bindings.node
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
```

So the install technically finishes but my app won't run. The console gives me:

```
Uncaught TypeError: exists is not a function
    at Function.getRoot (bundle.js:19670)
    at bindings (bundle.js:19572)
    at Object.<anonymous> (bundle.js:2853)
    at Object.<anonymous> (bundle.js:4311)
    at __webpack_require__ (bundle.js:1303)
    at fn (bundle.js:726)
    at Object.exports.byteLength (bundle.js:38902)
    at __webpack_require__ (bundle.js:1303)
    at fn (bundle.js:726)
    at Object.<anonymous> (bundle.js:38875)
```

This is definitely caused by ffi because I can take out the code that uses it and everything else runs fine. I don't know what to do from here.

**Comment by TooTallNate** [comment]
So I see you're using webpack. What are you using that for? Is this in the browser or in Node.js?

**Comment by EthanBogart** [comment]
That second error is in the console of my browser when I run watch and then start. I'm pretty sure it must be something wrong with the ffi build process.

The context is, I'm making an Electron app and using Webpack for the hot reloading.

Thank you for the help!

**Comment by EthanBogart** [comment]
@TooTallNate 

I have to admit most of my experience is in web programming, and I'm not much of a C++ guy. But if you could help point me in the direction of the problem I may be able to fork and fix it on my own.

I appreciate your help!

**Comment by EthanBogart** [comment]
Update if anyone else will have this issue in the future:

It seems libffi may not be compatible with compact unwinds. Trying to figure out how to fix it.

https://ghc.haskell.org/trac/ghc/ticket/5019

**Comment by EthanBogart** [comment]
So I fixed the warning by adding this settings to the `OS=="mac"` setting:

```
'OTHER_LDFLAGS': [
    '-Wl,-no_compact_unwind'
]
```

Those webpack errors are still there and it won't run but I'm getting closer. I'll close this issue but update it if I can figure it out so future people don't rip their hair out.

**Comment by EthanBogart** [comment]
https://github.com/rwaldron/johnny-five/issues/1101#issuecomment-213581938

That fixes the Webpack warnings I posted above, switching "mock-firmata" for "node-ffi."

**Comment by TooTallNate** [comment]
Honestly the whole compact unwind warning is a red herring. It always happens on MacOS, and node-ffi functions properly regardless.

The `Uncaught TypeError: exists is not a function` is your real error, and I'd recommend _not_ using webpack with this module. It's just not designed to work with webpack.

**Comment by EthanBogart** [comment]
Thank you for the response! I think I'm starting to figure that out.

Do you have any recommendations? I think I need to go in a slightly different direction.

**Comment by ghost** [comment]
uninstall your NodeJS and Python, 
download v10.16.3 LTS from https://nodejs.org/en/
(https://nodejs.org/dist/v10.16.3/node-v10.16.3-x64.msi or https://nodejs.org/dist/v10.16.3/node-v10.16.3-x86.msi)

update your windows (Windows Update).

make sure you have https://support.microsoft.com/en-ph/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi (download it from http://www.catalog.update.microsoft.com/search.aspx?q=kb3140245 )

Upgrade your powershell (for windows 7 x64 - download `Win7AndW2K8R2-KB3191566-x64.zip` ) : https://docs.microsoft.com/en-us/powershell/scripting/install/installing-windows-powershell?view=powershell-6#upgrading-existing-windows-powershell
and then download https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-preview.4/PowerShell-7.0.0-preview.4-win-x64.msi or https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-preview.4/PowerShell-7.0.0-preview.4-win-x86.msi (or newer from https://github.com/PowerShell/PowerShell/releases/ )

Finally download: https://github.com/eladkarako/mods/blob/store/NodeJS/resources/install_tools.bat and run it as admin, you might need to run it few times and reboot after each time because it also tries to install few windows-updates.

It will install Python that is suitable for compiling.

eventually you'll be able to just run `npm install ....` without any issues.
