### ISSUE TITLE
Error: Dynamic Linking Error: Win32 error 193 with node ffi

### ISSUE THREAD

**Issue by AnaisSrg** [node-ffi/node-ffi#410]
Hi everybody,

I try to call a C++ library with ffi module in node.js and I have this Error: Dynamic Linking Error: Win32 error 193 I know it significates that there is a problem of compatibility 32/64bits.

But I verified version of dll with dumpbin, it's in 64bits, I verified versions of dll referenced, they are in 64bits, I verified Node.js, it's in 64bits, my PC turn on 64bits... So, I don't understand.

If someone has an idea, I take !

Thanks :)

**Comment by chengdonglin** [comment]
have you resolve this problem? I have meet the same problem?

**Comment by yfjl** [comment]
have you resolve this problem? I have meet the same problem?
