### ISSUE TITLE
Weird callback behavior

### ISSUE THREAD

**Issue by jamrizzi** [node-ffi/node-ffi#412]
I am using a callback with node-ffi, but it is behaving strangely. Some code executes, and some code is just ignored. It's super weird.

```js
app.two = () => { console.log(2); };
app.register_on_activate(ffi.Callback('void', [type.GtkWidgetPtr], (window) => {
  console.log(1);
  app.two();
  console.log(3);
});
```

The result I get after the callback is 1 3. It completely skips 2. Every time I try and call a function outside of the callback it just ignores it. I have no errors or warnings. Any idea what is going on?

**Comment by jamrizzi** [comment]
To be more specific, it's when I'm calling the resolve of a promise. For some reason, everything inside the function runs, but the resolve won't run.

```js
return new Promise((resolve, reject) => {
  app.register_on_activate(ffi.Callback('void', [type.GtkWidgetPtr], (window) => {
    console.log(1);
    resolve();
    console.log(3);
  });
}).then(() => {
  // never resolves
  console.log(2);
});
```

**Comment by jamrizzi** [comment]
I figured out my problem. I was blocking the JavaScript event loop. You can see more details at the link below.

https://github.com/jamrizzi/node-gtk3/issues/4

**Comment by TooTallNate** [comment]
I'm glad you were able to figure it out ☺️
