### ISSUE TITLE
Is there simple way to set timeout for async call?

### ISSUE THREAD

**Issue by ludwiksh** [node-ffi/node-ffi#413]
For some unknown reasons, library I am trying to call will throw some exception internally which cannot be catch outside, in this case it will keeping running (using 99% capacity of CPU) and never return... so I am trying to control this situation by setting a timeout for my async like this:

`var handler = test.myCall.async(xxxx, (err, res) => `
`    //deal with results`
`})`
`setTimeout( () = > {   `
`  //nothing return in 5s, how to kill(handler) ? `
`}, 5000);`

thanks in advance!

**Comment by TooTallNate** [comment]
You would need to use a child processs and invoke `myCall` inside that sub-process. This is because there is no way to _cancel_ an async call in-flight.
