### ISSUE TITLE
Compiling source

### ISSUE THREAD

**Issue by jamrizzi** [node-ffi/node-ffi#417]
What is the best approach for cross-platform compiling a C library for node-ffi? Is it possible to use node-gyp?

**Comment by TooTallNate** [comment]
Ya you can use node-gyp. It's probably not the best approach but it works. See the [test case](https://github.com/node-ffi/node-ffi/blob/master/test/binding.gyp).

**Comment by jamrizzi** [comment]
What's the best approach?

**Comment by TooTallNate** [comment]
It depends on your application, there is no clear generic answer. There's meta build systems like cmake, Ninja, etc. If node-gyp works for you then use it!

**Comment by jamrizzi** [comment]
I'm wanting my c source code to build on when `npm install` is run.

**Comment by jamrizzi** [comment]
And it needs to work for Linux, Mac, and Windows

**Comment by jamrizzi** [comment]
Node-gyp gives me a dynamic linking error.

**Comment by TooTallNate** [comment]
See something like this:

 * https://github.com/TooTallNate/node-dlfcn/blob/master/test/binding.gyp
 * https://github.com/TooTallNate/node-dlfcn/blob/2db2bcd409c60afe3f028331e212409120a3a5b5/package.json#L7

**Comment by TooTallNate** [comment]
Gonna close since this isn't a node-ffi issue.
