### ISSUE TITLE
Bindings to An array of NULL terminated C strings got `Segmentation fault: 11`

### ISSUE THREAD

**Issue by alvinhui** [node-ffi/node-ffi#427]
Node-ffi is a great job! 

## Background

I'm going to write a Node bindings for [MITIE](https://github.com/mit-nlp/MITIE) which C++ library for NLP(Natural language processing). So I noticed node-ffi, and I saw:

> It can be used to create bindings to native libraries without writing any C++ code

It makes me feel excited because I do not have C ++ development experience.

I also know that [ffi isn't designed to work with C++ binaries](https://github.com/node-ffi/node-ffi/issues/311#issuecomment-233802030), But as what MITIE describes:

> MITIE's primary API is a C API which is documented in the [mitie.h](https://github.com/mit-nlp/MITIE/blob/master/mitielib/include/mitie.h) header file.

So I decided to have a try...

## Problem

The argument of a function is `char**`: An array of NULL terminated C strings, like this:

```cpp
int run (char** tokens)
{
    try
    {
        std::vector<std::string> words;
        for (unsigned long i = 0; tokens[i]; ++i)
            words.push_back(tokens[i]);

        return 1;
    }
    catch(...)
    {
        return 0;
    }
}
```
And this is what I did use ffi:

```javascript
const ffi = require('ffi');
const ArrayType = require('ref-array');

const StringArray = ArrayType('string')

const test = ffi.Library('test', {
  'run': [ 'int', [StringArray] ]
});

test.run(['a', 'b']);
```

But I got: `Segmentation fault: 11`.

I uploaded the sample code to [this repo](https://github.com/alvinhui/node-ffi-testing).

And in this repo you also can see I have wrote a Python bindings by [ctypes](https://docs.python.org/2/library/ctypes.html), It runs well.

Here is my operating environment:

* npm@3.10.10
* node@7.10.0
* darwin x64 17.0.0 
* MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
* macOS 10.13

**Comment by alvinhui** [comment]
My initial idea is that this has nothing to do with the type, it's related to memory allocation.

**Comment by alvinhui** [comment]
@TooTallNate @rbranson @kjunichi @unbornchikken

**Comment by sookie030** [comment]
char** in C == String* in nodejs.
So, I think you should change the type.

`const ffi = require('ffi');
**// const ArrayType = require('ref-array');**
const ref = require('ref');

**// const StringArray = ArrayType('string')**
const string_ptr = ref.refType('CString);

const test = ffi.Library('test', {
  **// 'run': [ 'int', [StringArray] ]**
  'run': [ 'int', [string_ptr] ]
});

test.run(['a', 'b']);`
