### ISSUE TITLE
Variadic function argument in C/C++

### ISSUE THREAD

**Issue by stern0** [node-ffi/node-ffi#436]
This isn't an issue but maybe lack of documentation on the subject.

I have a C function like the below, which has a variadic argument ```...``` as last argument.

```c
int message  (void *Interface, int code, char *format, ...)
```
I know the syntax in node ffi for this is ```{ varargs: true }``` and tried emulating that with:

```js
message: [ 'int', [ 'pointer', 'int', 'pointer', { varargs: true } ] ],
```

But I get the following error:

```
TypeError: could not determine a proper "type" from: {"varargs":true}
```

I saw this example [here](https://github.com/node-ffi/node-ffi/issues/136) but there's no info in the docs about this.

**Comment by ConPac** [comment]
The solution is as simple as moving the first ']' right after the last argument:
`message: [ 'int', [ 'pointer', 'int', 'pointer' ], { varargs: true } ],`

**Comment by stern0** [comment]
@ConPac thanks for the suggestion, I haven't looked at this since.
