### ISSUE TITLE
Can't Install FFI on Mac OS X

### ISSUE THREAD

**Issue by UsersDoProgram** [node-ffi/node-ffi#462]
When I run `sudo npm install ffi`  after installing node gyp I get the error on Mac OS X 10.13, 
> ref@1.3.5 install /Users/chris/node_modules/ref
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/chris/node_modules/ref/build'
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/chris/node_modules/ref
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Users/chris/package.json'
npm WARN chris No description
npm WARN chris No repository field.
npm WARN chris No README data
npm WARN chris No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for bluetooth-hci-socket@0.5.1: wanted {"os":"linux,android,win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chris/.npm/_logs/2018-03-29T02_17_21_196Z-debug.log
Is there any fix available for this?

**Comment by lukaskollmer** [comment]
`node-ffi` doesn't yet work with node 9.x. you'll have to either use node 8 or install `node-ffi` from the GitHub repo, instead of the npm package
