### ISSUE TITLE
Dynamic Linking Error: Win32 error 193

### ISSUE THREAD

**Issue by 2JJ1** [node-ffi/node-ffi#473]
var MyDLL = ffi.Library(__dirname+'\\HelloWorld.dll', {
  "HelloWorld": [ "void", [] ] //InjectDLL(string filepath) //No return value
});

On the first line of this code snippet, I get the error "Dynamic Linking Error: Win32 error 193". How can I get around this? I see that I can call the dll just fine in another program.

**Comment by AndreVicenteW** [comment]
Did you found the solution?

**Comment by TharunKumar1** [comment]
+1

**Comment by yft** [comment]
+1 Did you found the solution?

**Comment by fastCreator** [comment]
+1 Did you found the solution?

**Comment by yft** [comment]
It seems that cant run 32 dll on 64 os. The only way is getting a suitable dll for you os.

**Comment by yft** [comment]
1. install 32-bit node
2. reinstall node-gyp
3. reinstall npm dependencies

fix my problem.
