### ISSUE TITLE
How does cross-platform functionality work?

### ISSUE THREAD

**Issue by repl-chris** [node-ffi/node-ffi#497]
Sorry, I'm quite new to this project (and the ecosystem in general) and I'm having a little trouble understanding how it fits in. I'll explain what I'm wanting to do, and hopefully someone can help clarify my confusion.  

I'm trying to write an electron app which can run on windows, mac, and linux, and I'd like to use node-ffi to make calls to native OS libraries on each of those platforms. My understanding is that at build time using electron I can just generate the 3 different executables for the different OS's.  How does node-ffi fit into that?  I assume node-ffi is generating platform-specific binaries, will it somehow package the correct ones for the target OS?  Does/can node-ffi even generate (cross-compile) all the binaries I need?  Or do I need to somehow build my app on all 3 OS's to generate the necessary node-ffi binaries? If so, is it feasible to just build these binaries once and then reference them in my project (so I don't *always* need to compile on all 3 OS's)?

**Comment by Zayelion** [comment]
When you do `npm install` the platform it is done on is the platform it will make binaries for. So to have binaries for other systems you will need to build on those systems. So do not worry to much about `node-ffi` itself, The lib that is passed in your code base needs to be the correct one for the operating system. Use `os.platform()` to identify the operating system and pass the correct string representing the path to the lib.
