### ISSUE TITLE
ARMv8 64bit support?

### ISSUE THREAD

**Issue by Puddinglord** [node-ffi/node-ffi#504]
We are working with RTI DDS which uses node-ffi to call upon its own C++ libraries. This works great when we are on an x86 CPU but when we try to install ffi on an ARMv8 64bit machine it fails saying it can't find `<ffi.h>`. 

Has anyone else gotten ffi to successfully compile and run on an ARMv8 64bit CPU? If not does the team plan on adding support in the near future? Node-ffi is really critical for what we are doing.

Thanks!

**Comment by Puddinglord** [comment]
Could anyone help with this?

**Comment by k1tzu** [comment]
The main problem with node-ffi is **extremely** obsolete ffi library version it is linked to. So you need to replace that library with the fresh one. I'm having sex with rebuilding node-ffi for years. And I've noticed your issue only because I'm rebuilding it again and checked if it has been updated finally. But it is not. So search through issues here for my post I've posted a solution there for arm64 that can show you the way how to build the module.

**Comment by k1tzu** [comment]
oh i've found my message in my notes
```
Yes, the lib included is as old as dinosaurs. You need to get latest libffi from git to deps/libffi then cd deps/libffi ./autogen.sh;./configure --prefix=/usr;make;make install cp aarch64-unknown-linux-gnu/include/ffi.h /usr/include
cp aarch64-unknown-linux-gnu/include/ffitarget.h /usr/include
cp aarch64-unknown-linux-gnu/fficonfig.h /usr/include
then put https://github.com/node-ffi/node-ffi/blob/master/deps/libffi/libffi.gyp file to deps/libffi with a fix: line 118
      'conditions': [
        ['target_arch=="arm"', {
          'sources': [ 'src/arm/ffi.c' ],
          'conditions': [
            ['OS=="linux"', {
              'sources': [ 'src/arm/sysv.S' ]
            }]
          ]
        }, { # ia32 or x64
replace with
      'conditions': [
        ['target_arch=="arm64"', {
          'sources': [ 'src/aarch64/ffi.c' ],
          'conditions': [
            ['OS=="linux"', {
              'sources': [ 'src/aarch64/sysv.S' ]
            }]
          ]
        }, { # ia32 or x64
go back to module root cd ../../ and node-gyp rebuild
```

**Comment by zwy35** [comment]
Hi  Puddinglord & k1tzu，
 When I go to compile according to the method of k1tzu, encountered a new problem, have you met this problem, and  how to solve it, as follows：

> ffi@2.3.0 install /home/test/node-ffi
> node-gyp rebuild

make: Entering directory '/home/test/node-ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
../deps/libffi/src/closures.c: In function ‘allocate_space’:
../deps/libffi/src/closures.c:747:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       off_t to_write = (len < page_size) ? len : page_size;
                             ^
../deps/libffi/src/closures.c:747:48: warning: signed and unsigned type in conditional expression [-Wsign-compare]
       off_t to_write = (len < page_size) ? len : page_size;
                                                ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/aarch64/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/aarch64/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
../src/ffi.cc:21:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 NAN_MODULE_INIT(FFI::InitializeStaticFunctions) {
                ^
../src/ffi.cc:42:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 NAN_MODULE_INIT(FFI::InitializeBindings) {
                ^
../src/ffi.cc:174:11: error: expected constructor, destructor, or type conversion before ‘(’ token
 NAN_METHOD(FFI::FFIPrepCif) {
           ^
ffi_bindings.target.mk:108: recipe for target 'Release/obj.target/ffi_bindings/src/ffi.o' failed
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
make: Leaving directory '/home/test/node-ffi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node-v10.15.0-linux-arm64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.4.167-rockchip64
gyp ERR! command "/usr/local/node-v10.15.0-linux-arm64/bin/node" "/usr/local/node-v10.15.0-linux-arm64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/test/node-ffi
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-25T02_32_26_413Z-debug.log

Thanks!

**Comment by Puddinglord** [comment]
This issue was created because we were working with node on an arm based board. This is no longer the case and we are targeting x86. For this reason, I am closing this issue.

**Comment by rookiezh** [comment]
> 嗨，Puddinglord & k1tzu，当我按照k1tzu的方法去编译时，遇到了一个新问题，你有没有遇到过这个问题，以及如何解决，如下：
> 
> > ffi@2.3.0 安装 /home/test/node-ffi node-gyp 重建
> 
> make： 输入目录 '/home/test/node-ffi/build' CC（target） Release/obj.target/ffi/deps/libffi/src/prep_cif.o CC（target） Release/obj.target/ffi/deps/libffi/src/types.o CC（target） Release/obj.target/ffi/deps/libffi/src/raw_api.o CC（target） Release/obj.target/ffi/deps/libffi/src/java_raw_api.o CC（target） Release/obj.target/ffi/deps/libffi/src/closures.o ../deps/libffi/src/closures.c： 在函数 'allocate_space' 中： ../deps/libffi/src/closures.c：747：29： 警告：有符号和无符号整数表达式之间的比较 [-Wsign-compare] off_t to_write = （len < page_size） ？蓝 ： page_size; ^ ../deps/libffi/src/closures.c：747：48：警告：条件表达式 [-Wsign-compare] 中的有符号和无符号类型 off_t to_write = （len < page_size） ？蓝 ： page_size; ^ CC（target） Release/obj.target/ffi/deps/libffi/src/aarch64/ffi.o CC（target） Release/obj.target/ffi/deps/libffi/src/aarch64/sysv.o AR（target） Release/obj.target/deps/libffi/libffi.a COPY Release/libffi.a CXX（target） Release/obj.target/ffi_bindings/src/ffi.o ../src/ffi.cc：21：16：错误：在“（”令牌NAN_MODULE_INIT（FFI：：InitializeStaticFunctions） { ^ ../src/ffi.cc：42：16：错误：在“（”令牌NAN_MODULE_INIT（FFI：：InitializeBindings） { ^ ../src/ffi.cc：174：11：错误：预期的构造函数、析构函数或类型转换在“（”令牌NAN_METHOD（FFI：：FFIPrepCif）之前 { ^ ffi_bindings.target.mk：108： 目标“Release/obj.target/ffi_bindings/src/ffi.o”的配方失败：*** [Release/obj.target/ffi_bindings/src/ffi.o] 错误 1 使：离开目录“/home/test/node-ffi/build”gyp ERR！ 构建错误 gyp 错误！ 堆栈错误：失败退出代码：2 个 GYP 错误！stack at ChildProcess.onExit （/usr/local/node-v10.15.0-linux-arm64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js：262：23） gyp ERR！堆栈在 ChildProcess.emit （events.js：182：13） gyp 错误！堆栈在 Process.ChildProcess._handle.onexit （内部/child_process.js：240：12） gyp 错误！System Linux 4.4.167-rockchip64 gyp ERR！命令 “/usr/local/node-v10.15.0-linux-arm64/bin/node” “/usr/local/node-v10.15.0-linux-arm64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js” “rebuild” gyp ERR！cwd /home/test/node-ffi gyp ERR！节点 -v v10.15.0 GYP 错误！node-gyp -v v3.8.0 gyp ERR！不行 npm 错误！代码 电子生命周期 npm 错误！错误 1 npm 错误！ffi@2.3.0 安装： npm 错误！退出状态 1 npm 错误！呵呵！在 ffi@2.3.0 安装脚本中失败。呵呵！这可能不是 npm 的问题。上面可能有其他日志记录输出。`make``node-gyp rebuild`
> 
> 呵呵！可以在以下位置找到此运行的完整日志：npm ERR！/root/.npm/_logs/2019-02-25T02_32_26_413Z-debug.log
> 
> 谢谢！

hello, How did you solve it in the end?

**Comment by Puddinglord** [comment]
@rookiezh We moved over to an x86 architecture which didn't solve this problem but avoided it. Sorry, I can't be more helpful!
