### ISSUE TITLE
Binding.node is not a valid Win32 application (windows 10)

### ISSUE THREAD

**Issue by moialbla** [node-ffi/node-ffi#534]
Hi everyone,

I was trying to create an electron build for x32 and x64 and when I launch the x32 application electron throws the following message:
![image](https://user-images.githubusercontent.com/14232214/52956093-a9e15400-338e-11e9-9096-a8e6a9cc609a.png)

What am I doing wrong? Any opinions or suggestions?

Here my machine and project features:
- W10 64bits
- Node 10..13.0
- NPM 6.4.1
- electron 4.0.1
- electron-builder 20.38.2
- electron-packager 12.1.0
- electron-rebuild 1.8.2
- electron-reload 1.2.5
- node-gyp 4.0.0

Thank you in advance.

**Comment by joeyer** [comment]
Friend, is this problem solved?

**Comment by jacqueslorentz** [comment]
Hi,
What's was your issue? How do you resolved it?
Thanks!

**Comment by gzx-miller** [comment]
I have same issue, how to resolved it?
This codes hav'nt update two years, and a lots of issue have no one been fixed?
