### ISSUE TITLE
Error: Cannot find module 'node-ffi'

### ISSUE THREAD

**Issue by zensabbah** [node-ffi/node-ffi#541]
I'm new on NodeJS/ElectronJS.
I need to use User.dll functions.
My actual situation is:

Windows 10 on Parallels
Node -v = 10.15.3 (LTS)
NPM -v = 6.9.0

I installed:

`npm install --global --production windows-build-tools`

`npm install win32-api`
```
npm install ffi (gives me several "\ffi.cc(***): warning C4996: 'v8::Value::To
Object': .... deprecated)
```

 I added `var FFI = require('node-ffi');` in my "main.js" and when I try to compile with `npm start`

I obtain this error:
`Error: Cannot find module 'node-ffi'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)`

What's wrong?

**Comment by ghost** [comment]
@zensabbah  its just `ffi` now.
you can go to this repository which has an already built npm modules (and the `.node` built-binaries) and look for FFI folder under the `resources/` folder: https://github.com/eladkarako/already-built-npm

**Comment by zensabbah** [comment]
Thanks!

**Comment by ghost** [comment]
@zensabbah, also, here is a simplified 'all included' example (uses `MessageBoxW` from `user32.dll`)
https://github.com/eladkarako/nodejs_ffi_winapi_messageboxw
