### ISSUE TITLE
Problem with windows data types

### ISSUE THREAD

**Issue by karliky** [node-ffi/node-ffi#58]
Hey folks

I'm trying to implement a wrapper for windows API, so as you know there are some custom Windows data types that aren't listed on the wiki (Appendix: Type List) like:

```
DWORD
BOOL
```

I've searched over the net and I found this page http://fossies.org/dox/Python-3.2.3/wintypes_8py_source.html:

So if i'm not wrong...

```
DWORD = ulong
BOOL = byte
```

Well, i've implemented 2 function from user32.dll and these are working perfectly:

```
var user32 = new FFI.Library("user32", {
    "FindWindowA": [ "uint32", [ "string", "string" ] ],
    "GetWindowThreadProcessId" : ["int32", ['int32','pointer']]
  });
```

But now, i'm using the handle from GetWindowThreadProcessId and it's not working on OpenProcess()

```
var kernel32 = new FFI.Library("Kernel32", {
    "OpenProcess": [ "int32", [ "ulong","byte","ulong"] ],
  });
```

Full source code:

```

  var user32 = new FFI.Library("user32", {
    "FindWindowA": [ "uint32", [ "string", "string" ] ],
    "GetWindowThreadProcessId" : ["int32", ['int32','pointer']]
  });

  var kernel32 = new FFI.Library("Kernel32", {
    "OpenProcess": [ "int32", [ "ulong","byte","ulong"] ],
  });

  var calculatorH = user32.FindWindowA(null, "Calculadora");

  console.log("hWnd: "+calculatorH)

  var calculatorP = user32.GetWindowThreadProcessId(calculatorH, null);

  console.log("Proccess ID: "+calculatorP)

  //  PROCESS_ALL_ACCESS == 2097151
  /*
  HANDLE WINAPI OpenProcess(
    __in  DWORD dwDesiredAccess,
    __in  BOOL bInheritHandle,
    __in  DWORD dwProcessId
  );
  */
  var processHandle = kernel32.OpenProcess(2097151,0,calculatorP)

  console.log("hProcess: "+processHandle)

```

This is the result from Node.js
http://i49.tinypic.com/5boinl.png
and this is the working expected result written in C++
http://i47.tinypic.com/eh0lc2.png

So the problem is that OpenProcess is not working and I think related about windows data types or somthing that i'm doing wrong....

**Comment by consense** [comment]
Just in case someone else comes upon this issue via googling:
the problem of the OP stems from wrong usage of the GetWindowThreadProcessId.
`var calculatorP = user32.GetWindowThreadProcessId(calculatorH, null);`
does not populate calculatorP  with the processId, but rather with the thread id (which in turn leads to an empty result from `OpenProcess`). 
The processId can be fetched by using the second parameter to GetWindowThreadProcessId (output param)
