### ISSUE TITLE
ffi not Support electron6、7, anynoe can help us!! >_<   >_<

### ISSUE THREAD

**Issue by whitemiaool** [node-ffi/node-ffi#582]
[node-ffi](https://github.com/lxe/node-ffi/tree/node-12), electron5 is ok,  but not support6 and 7,  @lxe ,can you help us!

**Comment by alwxkxk** [comment]
[node-ffi-napi](https://github.com/node-ffi-napi/node-ffi-napi) support  Node12, Electron 7.

**Comment by whitemiaool** [comment]
> [node-ffi-napi](https://github.com/node-ffi-napi/node-ffi-napi) support Node12, Electron 7.
get it
