### ISSUE TITLE
electron 9.0.0, node -v v12.7.0 ffi install error, i have set python path so on.

### ISSUE THREAD

**Issue by jhotel** [node-ffi/node-ffi#593]
KeyError: '2019'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:348:16)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\SvnHome\Kongur\trunk\peripheral-controller\node_modules\ref
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v v3.8.0

Current node-gyp is v7

**Comment by jhotel** [comment]
> > gyp ERR! node-gyp -v v3.8.0
> 
> Current node-gyp is v7

thank you, you are right

**Comment by jhotel** [comment]
> > gyp ERR! node-gyp -v v3.8.0
> 
> Current node-gyp is v7

thanks cclauss, you are right

**Comment by cclauss** [comment]
Given #596, you might want to try to add `NODE_GYP_FORCE_PYTHON=python2`to your command.

Python 2 is dead but node-ffi might still _need_ it instead of the current Python v3.8.5.
