### ISSUE TITLE
Problem loading a shared library with dependencies 

### ISSUE THREAD

**Issue by marcellop71** [node-ffi/node-ffi#80]
Hi, the issue I'm facing is the following:
loading some libB.so that uses libA.so
(so that libB has some U symbols that A defines and implements).
If I try to load libB with ffi (see below some coffescriped code),
I'm blocked by a ''Dynamic Linking Error':
'undefined symbol: <some symbol not defined in B but in A>.
Any hint ?
Sorry to post such a basic issue.
Thank you, ciao, M.

(*) libB = ffi.Library 'libB' or libB = ffi.DynamicLibrary 'libB.so'

**Comment by Ob1To** [comment]
I'm having the same problem 5 years later, but now I'm using ffi.Library. Can you help me, please?

**Comment by jay11ca39** [comment]
@TooTallNate ,
I was trying to include the flags like this:
```
var RTLD_NOW = ffi.Library.FLAGS.RTLD_NOW;
var RTLD_GLOBAL = ffi.Library.FLAGS.RTLD_GLOBAL;
```
                          
But i got the below error:
`TypeError: Cannot read property 'RTLD_NOW' of undefined`

seems flags got changed, can you please let me know how to use the flag in latest node-ffi code.
